# Generated by Django 6.0 on 2026-08-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_alter_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATCH', 'مسابقات'), ('TRANSFER', 'نقل و انتقالات'), ('GACHA', 'گاشا'), ('SYSTEM', 'سیستم')], default='SYSTEM', max_length=15, verbose_name='دسته‌بندی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(blank=True, verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'اعلامیه',
                'verbose_name_plural': 'اعلامیه‌ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
