# Generated by Django 6.0.7 on 2026-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('MATCH', 'مسابقات'), ('TRANSFER', 'نقل و انتقالات'), ('GACHA', 'گاشا'), ('SYSTEM', 'سیستم'), ('REWARD', 'پاداش و جایزه')], default='SYSTEM', max_length=15, verbose_name='دسته\u200cبندی'),
        ),
    ]
