"""
Self-contained Production Player Stats & Position Updater
Run directly inside backend container or via Django manage.py shell.
"""
import os
import sys
import django
import unicodedata
import re

sys.stdout.reconfigure(encoding='utf-8')
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.db import transaction
from teams.models import Team, Player

def clean_name(s):
    if not s:
        return ''
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    s = s.replace('-', ' ').replace('.', ' ').replace("'", '').replace('’', '').replace('`', '').strip().lower()
    return re.sub(r'\s+', ' ', s)

def calculate_rarity(ovr: int, pot: int) -> str:
    if ovr >= 88 or pot >= 92:
        return 'LEGENDARY'
    elif ovr >= 84 or pot >= 88:
        return 'EPIC'
    elif ovr >= 80:
        return 'RARE'
    return 'REGULAR'

PLAYER_DATA = [
    ('Liverpool', 'Alisson Becker', 'GK', 87),
    ('Liverpool', 'Mohamed Salah', 'RWF', 87),
    ('Liverpool', 'Dominik Szoboszlai', 'AMF', 87),
    ('Liverpool', 'Virgil van Dijk', 'CB', 86),
    ('Liverpool', 'Cody Gakpo', 'LWF', 86),
    ('Liverpool', 'Alexander Isak', 'CF', 86),
    ('Liverpool', 'Ibrahima Konaté', 'CB', 85),
    ('Liverpool', 'Alexis Mac Allister', 'CMF', 85),
    ('Liverpool', 'Ryan Gravenberch', 'DMF', 85),
    ('Liverpool', 'Andrew Robertson', 'LB', 84),
    ('Liverpool', 'Giorgi Mamardashvili', 'GK', 84),
    ('Liverpool', 'Hugo Ekitiké', 'CF', 84),
    ('Liverpool', 'Jeremie Frimpong', 'RB', 83),
    ('Liverpool', 'Curtis Jones', 'CMF', 83),
    ('Liverpool', 'Florian Wirtz', 'AMF', 83),
    ('Liverpool', 'Harvey Elliott', 'AMF', 82),
    ('Liverpool', 'Joe Gomez', 'CB', 81),
    ('Liverpool', 'Milos Kerkez', 'LB', 81),
    ('Liverpool', 'Conor Bradley', 'RB', 81),
    ('Liverpool', 'Federico Chiesa', 'RWF', 81),
    ('Liverpool', 'K. Tsimikas', 'LB', 81),
    ('Liverpool', 'Wataru Endo', 'DMF', 79),
    ('Liverpool', 'Freddie Woodman', 'GK', 77),
    ('Liverpool', 'Stefan Bajcetic', 'DMF', 77),
    ('Liverpool', 'Vitezslav Jaros', 'GK', 77),
    ('Liverpool', 'Rhys Williams', 'CB', 74),
    ('Liverpool', 'Trey Nyoni', 'AMF', 74),
    ('Liverpool', 'Harvey Davies', 'GK', 73),
    ('Liverpool', 'Giovanni Leoni', 'CB', 73),
    ('Liverpool', 'James McConnell', 'CMF', 73),
    ('Liverpool', 'Calvin Ramsay', 'RB', 72),
    ('Liverpool', 'Rio Ngumoha', 'LWF', 70),
    ('Liverpool', 'Bobby Clark', 'CMF', 67),
    ('FC Bayern München', 'Harry Kane', 'CF', 89),
    ('FC Bayern München', 'Michael Olise', 'RWF', 87),
    ('FC Bayern München', 'Joshua Kimmich', 'DMF', 86),
    ('FC Bayern München', 'Luis Díaz', 'LWF', 86),
    ('FC Bayern München', 'Jamal Musiala', 'AMF', 86),
    ('FC Bayern München', 'Manuel Neuer', 'GK', 85),
    ('FC Bayern München', 'Kim Min-jae', 'CB', 85),
    ('FC Bayern München', 'Dayot Upamecano', 'CB', 84),
    ('FC Bayern München', 'Alphonso Davies', 'LB', 84),
    ('FC Bayern München', 'Leon Goretzka', 'CMF', 84),
    ('FC Bayern München', 'Serge Gnabry', 'LWF', 84),
    ('FC Bayern München', 'João Palhinha', 'DMF', 83),
    ('FC Bayern München', 'Konrad Laimer', 'RB', 83),
    ('FC Bayern München', 'Aleksandar Pavlović', 'DMF', 83),
    ('FC Bayern München', 'Jonathan Tah', 'CB', 83),
    ('FC Bayern München', 'Raphaël Guerreiro', 'LB', 82),
    ('FC Bayern München', 'Hiroki Ito', 'CB', 80),
    ('FC Bayern München', 'Josip Stanišić', 'RB', 80),
    ('FC Bayern München', 'Alexander Nübel', 'GK', 80),
    ('FC Bayern München', 'Bryan Zaragoza', 'LWF', 79),
    ('FC Bayern München', 'Sven Ulreich', 'GK', 79),
    ('FC Bayern München', 'Sacha Boey', 'RB', 79),
    ('FC Bayern München', 'Jonas Urbig', 'GK', 76),
    ('FC Bayern München', 'Tom Bischof', 'CMF', 76),
    ('FC Bayern München', 'Daniel Peretz', 'GK', 76),
    ('FC Bayern München', 'Lennart Karl', 'AMF', 75),
    ('FC Bayern München', 'Jonah Kusi-Asare', 'CF', 74),
    ('FC Bayern München', 'Arijon Ibrahimović', 'AMF', 72),
    ('Arsenal', 'Bukayo Saka', 'RWF', 88),
    ('Arsenal', 'William Saliba', 'CB', 87),
    ('Arsenal', 'Declan Rice', 'CMF', 87),
    ('Arsenal', 'Martin Ødegaard', 'AMF', 86),
    ('Arsenal', 'David Raya', 'GK', 85),
    ('Arsenal', 'Gabriel Magalhães', 'CB', 85),
    ('Arsenal', 'Martín Zubimendi', 'DMF', 85),
    ('Arsenal', 'Gabriel Martinelli', 'LWF', 85),
    ('Arsenal', 'Viktor Gyökeres', 'CF', 85),
    ('Arsenal', 'Kai Havertz', 'CF', 85),
    ('Arsenal', 'Ben White', 'RB', 84),
    ('Arsenal', 'Mikel Merino', 'CMF', 84),
    ('Arsenal', 'Eberechi Eze', 'AMF', 84),
    ('Arsenal', 'Gabriel Jesus', 'CF', 84),
    ('Arsenal', 'Riccardo Calafiori', 'LB', 83),
    ('Arsenal', 'Myles Lewis-Skelly', 'LB', 83),
    ('Arsenal', 'Leandro Trossard', 'LWF', 83),
    ('Arsenal', 'Noni Madueke', 'RWF', 82),
    ('Arsenal', 'Kepa Arrizabalaga', 'GK', 81),
    ('Arsenal', 'Jurrien Timber', 'RB', 81),
    ('Arsenal', 'O. Zinchenko', 'LB', 81),
    ('Arsenal', 'Jakub Kiwior', 'CB', 81),
    ('Arsenal', 'Christian Nørgaard', 'DMF', 80),
    ('Arsenal', 'Reiss Nelson', 'LWF', 79),
    ('Arsenal', 'Cristhian Mosquera', 'CB', 77),
    ('Arsenal', 'Max Dowman', 'AMF', 73),
    ('Arsenal', 'Marli Salmon', 'CB', 72),
    ('Chelsea', 'Cole Palmer', 'AMF', 87),
    ('Chelsea', 'Enzo Fernández', 'CMF', 86),
    ('Chelsea', 'Pedro Neto', 'RWF', 85),
    ('Chelsea', 'Robert Sánchez', 'GK', 84),
    ('Chelsea', 'Marc Cucurella', 'LB', 84),
    ('Chelsea', 'Moisés Caicedo', 'DMF', 84),
    ('Chelsea', 'Levi Colwill', 'CB', 83),
    ('Chelsea', 'Reece James', 'RB', 83),
    ('Chelsea', 'João Pedro', 'CF', 83),
    ('Chelsea', 'Estevão', 'RWF', 83),
    ('Chelsea', 'Axel Disasi', 'CB', 83),
    ('Chelsea', 'Wesley Fofana', 'CB', 82),
    ('Chelsea', 'Alejandro Garnacho', 'LWF', 82),
    ('Chelsea', 'Jamie Gittens', 'LWF', 82),
    ('Chelsea', 'Nicolas Jackson', 'CF', 82),
    ('Chelsea', 'Trevoh Chalobah', 'CB', 81),
    ('Chelsea', 'Roméo Lavia', 'DMF', 81),
    ('Chelsea', 'Mykhaylo Mudryk', 'LWF', 81),
    ('Chelsea', 'Andrey Santos', 'CMF', 80),
    ('Chelsea', 'Filip Jörgensen', 'GK', 80),
    ('Chelsea', 'Tosin Adarabioyo', 'CB', 80),
    ('Chelsea', 'Benoît Badiashile', 'CB', 80),
    ('Chelsea', 'Jorrel Hato', 'LB', 80),
    ('Chelsea', 'Malo Gusto', 'RB', 80),
    ('Chelsea', 'Dário Essugo', 'DMF', 79),
    ('Chelsea', 'Liam Delap', 'CF', 78),
    ('Chelsea', 'Aaron Anselmino', 'CB', 78),
    ('Chelsea', 'Gabriel Slonina', 'GK', 77),
    ('Chelsea', 'Josh Acheampong', 'RB', 77),
    ('Chelsea', 'Marc Guiu', 'CF', 76),
    ('Chelsea', 'Tyrique George', 'LWF', 76),
    ('Chelsea', 'D. Datro Fofana', 'CF', 76),
    ('Chelsea', 'Caleb Wiley', 'LB', 75),
    ('Chelsea', 'Mamadou Sarr', 'CB', 74),
    ('Chelsea', 'T. Sharman-Lowe', 'GK', 70),
    ('Manchester United', 'Bruno Fernandes', 'AMF', 87),
    ('Manchester United', 'Bryan Mbeumo', 'RWF', 85),
    ('Manchester United', 'Lisandro Martínez', 'CB', 84),
    ('Manchester United', 'Amad Diallo', 'RWF', 84),
    ('Manchester United', 'Matthijs de Ligt', 'CB', 83),
    ('Manchester United', 'Diogo Dalot', 'RB', 83),
    ('Manchester United', 'Benjamin Šeško', 'CF', 83),
    ('Manchester United', 'Matheus Cunha', 'CF', 83),
    ('Manchester United', 'André Onana', 'GK', 83),
    ('Manchester United', 'Manuel Ugarte', 'DMF', 82),
    ('Manchester United', 'Mason Mount', 'AMF', 82),
    ('Manchester United', 'Noussair Mazraoui', 'RB', 82),
    ('Manchester United', 'Jadon Sancho', 'LWF', 81),
    ('Manchester United', 'Leny Yoro', 'CB', 81),
    ('Manchester United', 'Kobbie Mainoo', 'CMF', 81),
    ('Manchester United', 'Luke Shaw', 'LB', 81),
    ('Manchester United', 'Casemiro', 'DMF', 81),
    ('Manchester United', 'Joshua Zirkzee', 'CF', 81),
    ('Manchester United', 'Rasmus Højlund', 'CF', 81),
    ('Manchester United', 'Senne Lammens', 'GK', 80),
    ('Manchester United', 'Harry Maguire', 'CB', 80),
    ('Manchester United', 'Patrick Dorgu', 'LB', 79),
    ('Manchester United', 'Tyrell Malacia', 'LB', 79),
    ('Manchester United', 'Altay Bayındır', 'GK', 78),
    ('Manchester United', 'Ayden Heaven', 'CB', 78),
    ('Manchester United', 'Diego León', 'LB', 76),
    ('Manchester United', 'Chido Obi-Martin', 'CF', 76),
    ('Manchester United', 'Toby Collyer', 'DMF', 76),
    ('Manchester City', 'Erling Haaland', 'CF', 91),
    ('Manchester City', 'Rodri', 'DMF', 89),
    ('Manchester City', 'G. Donnarumma', 'GK', 87),
    ('Manchester City', 'Rúben Dias', 'CB', 87),
    ('Manchester City', 'Phil Foden', 'RWF', 85),
    ('Manchester City', 'Jérémy Doku', 'LWF', 85),
    ('Manchester City', 'Tijjani Reijnders', 'CMF', 85),
    ('Manchester City', 'Bernardo Silva', 'AMF', 84),
    ('Manchester City', 'Rayan Cherki', 'AMF', 84),
    ('Manchester City', 'Nico González', 'CMF', 84),
    ('Manchester City', 'Omar Marmoush', 'CF', 84),
    ('Manchester City', 'Jack Grealish', 'LWF', 83),
    ('Manchester City', 'John Stones', 'CB', 83),
    ('Manchester City', 'Rico Lewis', 'RB', 83),
    ('Manchester City', 'Joško Gvardiol', 'CB', 83),
    ('Manchester City', 'Nathan Aké', 'CB', 83),
    ('Manchester City', 'Marc Guéhi', 'CB', 83),
    ('Manchester City', 'Matheus Nunes', 'RB', 83),
    ('Manchester City', 'Savinho', 'RWF', 83),
    ('Manchester City', 'Rayan Aït-Nouri', 'LB', 82),
    ('Manchester City', 'Mateo Kovačić', 'CMF', 82),
    ('Manchester City', 'Antoine Semenyo', 'RWF', 82),
    ('Manchester City', 'Manuel Akanji', 'CB', 82),
    ('Manchester City', 'Abdukodir Khusanov', 'CB', 81),
    ('Manchester City', "Nico O'Reilly", 'LB', 81),
    ('Manchester City', 'Vitor Reis', 'CB', 81),
    ('Manchester City', 'Kalvin Phillips', 'DMF', 81),
    ('Manchester City', 'James Trafford', 'GK', 80),
    ('Real Madrid', 'Kylian Mbappé', 'CF', 91),
    ('Real Madrid', 'Vinícius Júnior', 'LWF', 89),
    ('Real Madrid', 'Jude Bellingham', 'AMF', 89),
    ('Real Madrid', 'Thibaut Courtois', 'GK', 88),
    ('Real Madrid', 'Federico Valverde', 'CMF', 87),
    ('Real Madrid', 'T. Alexander-Arnold', 'RB', 86),
    ('Real Madrid', 'Rodrygo', 'RWF', 86),
    ('Real Madrid', 'Antonio Rüdiger', 'CB', 85),
    ('Real Madrid', 'Aurélien Tchouaméni', 'DMF', 85),
    ('Real Madrid', 'David Alaba', 'CB', 84),
    ('Real Madrid', 'Éder Militão', 'CB', 84),
    ('Real Madrid', 'Eduardo Camavinga', 'CMF', 84),
    ('Real Madrid', 'Arda Güler', 'AMF', 84),
    ('Real Madrid', 'Dani Carvajal', 'RB', 83),
    ('Real Madrid', 'Brahim Díaz', 'RWF', 83),
    ('Real Madrid', 'Andriy Lunin', 'GK', 82),
    ('Real Madrid', 'Dean Huijsen', 'CB', 82),
    ('Real Madrid', 'Ferland Mendy', 'LB', 81),
    ('Real Madrid', 'Álvaro Carreras', 'LB', 81),
    ('Real Madrid', 'Dani Ceballos', 'CMF', 81),
    ('Real Madrid', 'F. Mastantuono', 'RWF', 81),
    ('Real Madrid', 'Raúl Asencio', 'CB', 80),
    ('Real Madrid', 'Fran García', 'LB', 79),
    ('Real Madrid', 'Thiago Pitarch', 'CMF', 79),
    ('Real Madrid', 'Gonzalo García', 'CF', 78),
    ('Real Madrid', 'Fran González', 'GK', 74),
    ('Real Madrid', 'Mario Martín', 'DMF', 72),
    ('Real Madrid', 'César Palacios', 'AMF', 72),
    ('FC Barcelona', 'Raphinha', 'LWF', 89),
    ('FC Barcelona', 'Lamine Yamal', 'RWF', 88),
    ('FC Barcelona', 'R. Lewandowski', 'CF', 88),
    ('FC Barcelona', 'Jules Koundé', 'RB', 86),
    ('FC Barcelona', 'Pedri', 'CMF', 86),
    ('FC Barcelona', 'Ronald Araújo', 'CB', 85),
    ('FC Barcelona', 'Dani Olmo', 'AMF', 85),
    ('FC Barcelona', 'Frenkie de Jong', 'CMF', 85),
    ('FC Barcelona', 'Joan García', 'GK', 84),
    ('FC Barcelona', 'Alejandro Baldé', 'LB', 84),
    ('FC Barcelona', 'Gavi', 'CMF', 84),
    ('FC Barcelona', 'Marcus Rashford', 'LWF', 84),
    ('FC Barcelona', 'Pau Cubarsí', 'CB', 83),
    ('FC Barcelona', 'Marc Casadó', 'DMF', 83),
    ('FC Barcelona', 'Fermín López', 'AMF', 83),
    ('FC Barcelona', 'Marc Ter Stegen', 'GK', 83),
    ('FC Barcelona', 'Andreas Christensen', 'CB', 82),
    ('FC Barcelona', 'Eric García', 'CB', 82),
    ('FC Barcelona', 'Ferran Torres', 'CF', 82),
    ('FC Barcelona', 'Wojciech Szczesny', 'GK', 81),
    ('FC Barcelona', 'Ansu Fati', 'LWF', 80),
    ('FC Barcelona', 'Iñaki Peña', 'GK', 79),
    ('FC Barcelona', 'Marc Bernal', 'DMF', 78),
    ('FC Barcelona', 'Héctor Fort', 'RB', 78),
    ('FC Barcelona', 'Roony Bardghji', 'RWF', 76),
    ('FC Barcelona', 'Gerard Martín', 'LB', 76),
    ('FC Barcelona', 'Ander Astralaga', 'GK', 72),
    ('FC Barcelona', 'Diego Kochen', 'GK', 70),
    ('Paris Saint-Germain', 'K. Kvaratskhelia', 'LWF', 87),
    ('Paris Saint-Germain', 'Désiré Doué', 'RWF', 86),
    ('Paris Saint-Germain', 'Ousmane Dembélé', 'CF', 86),
    ('Paris Saint-Germain', 'Achraf Hakimi', 'RB', 85),
    ('Paris Saint-Germain', 'Nuno Mendes', 'LB', 85),
    ('Paris Saint-Germain', 'Vitinha', 'DMF', 85),
    ('Paris Saint-Germain', 'Fabián Ruiz', 'CMF', 85),
    ('Paris Saint-Germain', 'Lucas Chevalier', 'GK', 84),
    ('Paris Saint-Germain', 'Marquinhos', 'CB', 84),
    ('Paris Saint-Germain', 'Lucas Hernández', 'LB', 84),
    ('Paris Saint-Germain', 'Warren Zaïre-Emery', 'CMF', 84),
    ('Paris Saint-Germain', 'Bradley Barcola', 'LWF', 84),
    ('Paris Saint-Germain', 'Gonçalo Ramos', 'CF', 83),
    ('Paris Saint-Germain', 'Willian Pacho', 'CB', 83),
    ('Paris Saint-Germain', 'Randal Kolo Muani', 'CF', 82),
    ('Paris Saint-Germain', 'João Neves', 'CMF', 82),
    ('Paris Saint-Germain', 'Ilya Zabarnyi', 'CB', 81),
    ('Paris Saint-Germain', 'Lee Kang-in', 'AMF', 81),
    ('Paris Saint-Germain', 'Matvey Safonov', 'GK', 80),
    ('Paris Saint-Germain', 'Lucas Beraldo', 'CB', 80),
    ('Paris Saint-Germain', 'Ibrahim Mbaye', 'RWF', 77),
    ('Paris Saint-Germain', 'Senny Mayulu', 'CMF', 75),
    ('Paris Saint-Germain', 'Noham Kamara', 'CB', 74),
    ('Paris Saint-Germain', 'Renato Marin', 'GK', 73),
    ('Paris Saint-Germain', 'Yoram Zague', 'RB', 73),
    ('Paris Saint-Germain', 'Dro Fernández', 'AMF', 69),
    ('Paris Saint-Germain', 'Quentin Ndjantou', 'LWF', 67),
    ('Juventus', 'Bremer', 'CB', 85),
    ('Juventus', 'Teun Koopmeiners', 'DMF', 85),
    ('Juventus', 'Michele Di Gregorio', 'GK', 84),
    ('Juventus', 'Jonathan David', 'CF', 84),
    ('Juventus', 'Douglas Luiz', 'CMF', 83),
    ('Juventus', 'Manuel Locatelli', 'DMF', 83),
    ('Juventus', 'Dušan Vlahović', 'CF', 83),
    ('Juventus', 'Pierre Kalulu', 'CB', 82),
    ('Juventus', 'Khéphren Thuram', 'CMF', 82),
    ('Juventus', 'Federico Gatti', 'CB', 81),
    ('Juventus', 'Francisco Conceição', 'RWF', 81),
    ('Juventus', 'Andrea Cambiaso', 'LB', 81),
    ('Juventus', 'Weston McKennie', 'CMF', 81),
    ('Juventus', 'Fabio Miretti', 'CMF', 81),
    ('Juventus', 'Edon Zhegrova', 'RWF', 81),
    ('Juventus', 'Kenan Yildiz', 'LWF', 81),
    ('Juventus', 'Arkadiusz Milik', 'CF', 81),
    ('Juventus', 'Nico González', 'LWF', 81),
    ('Juventus', 'Mattia Perin', 'GK', 80),
    ('Juventus', 'Lloyd Kelly', 'CB', 79),
    ('Juventus', 'Filip Kostić', 'LMF', 78),
    ('Juventus', 'Juan Cabal', 'LB', 78),
    ('Juventus', 'Daniele Rugani', 'CB', 77),
    ('Juventus', 'Timothy Weah', 'RMF', 77),
    ('Juventus', 'Vasilije Adžić', 'AMF', 76),
    ('Juventus', 'Jonas Rouhi', 'LB', 74),
    ('Juventus', 'Carlo Pinsoglio', 'GK', 72),
    ('Juventus', 'Emanuele Pecorino', 'CF', 66),
    ('Tottenham Hotspur', 'Rodrigo Bentancur', 'DMF', 86),
    ('Tottenham Hotspur', 'James Maddison', 'AMF', 86),
    ('Tottenham Hotspur', 'Guglielmo Vicario', 'GK', 85),
    ('Tottenham Hotspur', 'Cristian Romero', 'CB', 85),
    ('Tottenham Hotspur', 'Dejan Kulusevski', 'AMF', 84),
    ('Tottenham Hotspur', 'Pedro Porro', 'RB', 83),
    ('Tottenham Hotspur', 'Destiny Udogie', 'LB', 83),
    ('Tottenham Hotspur', 'Richarlison', 'CF', 83),
    ('Tottenham Hotspur', 'Conor Gallagher', 'CMF', 83),
    ('Tottenham Hotspur', 'Dominic Solanke', 'CF', 83),
    ('Tottenham Hotspur', 'Micky van de Ven', 'CB', 82),
    ('Tottenham Hotspur', 'Xavi Simons', 'AMF', 82),
    ('Tottenham Hotspur', 'Kevin Danso', 'CB', 82),
    ('Tottenham Hotspur', 'Pape Matar Sarr', 'CMF', 82),
    ('Tottenham Hotspur', 'Mohammed Kudus', 'RWF', 81),
    ('Tottenham Hotspur', 'Yves Bissouma', 'DMF', 81),
    ('Tottenham Hotspur', 'Mathys Tel', 'CF', 81),
    ('Tottenham Hotspur', 'Manor Solomon', 'LWF', 80),
    ('Tottenham Hotspur', 'Ben Davies', 'CB', 79),
    ('Tottenham Hotspur', 'Antonín Kinský', 'GK', 78),
    ('Tottenham Hotspur', 'Djed Spence', 'LB', 78),
    ('Tottenham Hotspur', 'Radu Drăgușin', 'CB', 78),
    ('Tottenham Hotspur', 'Lucas Bergvall', 'CMF', 78),
    ('Tottenham Hotspur', 'Wilson Odobert', 'RWF', 78),
    ('Tottenham Hotspur', 'Archie Gray', 'CB', 77),
    ('Tottenham Hotspur', 'Mikey Moore', 'LWF', 77),
    ('Tottenham Hotspur', 'Ashley Phillips', 'CB', 75),
    ('Tottenham Hotspur', 'Kota Takai', 'CB', 74),
    ('Atlético Madrid', 'Julián Alvarez', 'CF', 86),
    ('Atlético Madrid', 'Álex Baena', 'LWF', 85),
    ('Atlético Madrid', 'Ademola Lookman', 'SS', 85),
    ('Atlético Madrid', 'Jan Oblak', 'GK', 84),
    ('Atlético Madrid', 'Antoine Griezmann', 'SS', 84),
    ('Atlético Madrid', 'Robin Le Normand', 'CB', 83),
    ('Atlético Madrid', 'José Giménez', 'CB', 83),
    ('Atlético Madrid', 'Marcos Llorente', 'RB', 83),
    ('Atlético Madrid', 'Alexander Sørloth', 'CF', 83),
    ('Atlético Madrid', 'Thiago Almada', 'LWF', 83),
    ('Atlético Madrid', 'Nahuel Molina', 'RB', 82),
    ('Atlético Madrid', 'Koke', 'CMF', 82),
    ('Atlético Madrid', 'Juan Musso', 'GK', 82),
    ('Atlético Madrid', 'Dávid Hancko', 'CB', 82),
    ('Manchester City', 'Claudio Echeverri', 'AMF', 78),
    ('Manchester City', 'Marcus Bettinelli', 'GK', 77),
    ('Manchester City', 'Sverre Nypan', 'CMF', 76),
    ('Manchester City', 'Max Alleyne', 'CB', 72),
    ('Inter', 'Alessandro Bastoni', 'CB', 86),
    ('Inter', 'Nicolò Barella', 'CMF', 86),
    ('Inter', 'Lautaro Martínez', 'CF', 86),
    ('Inter', 'Marcus Thuram', 'CF', 86),
    ('Inter', 'Yann Sommer', 'GK', 85),
    ('Inter', 'Hakan Çalhanoğlu', 'CMF', 84),
    ('Inter', 'Federico Dimarco', 'LB', 84),
    ('Inter', 'Denzel Dumfries', 'RB', 84),
    ('Inter', 'Francesco Acerbi', 'CB', 83),
    ('Inter', 'Piotr Zieliński', 'CMF', 83),
    ('Inter', 'Davide Frattesi', 'CMF', 83),
    ('Inter', 'Benjamin Pavard', 'CB', 83),
    ('Inter', 'Stefan de Vrij', 'CB', 82),
    ('Inter', 'Carlos Augusto', 'LB', 82),
    ('Inter', 'Matteo Darmian', 'RB', 82),
    ('Inter', 'Henrikh Mkhitaryan', 'CMF', 82),
    ('Inter', 'Josep Martínez', 'GK', 80),
    ('Inter', 'Yann Bisseck', 'CB', 80),
    ('Inter', 'Kristjan Asllani', 'DMF', 78),
    ('Inter', 'Luis Henrique', 'RMF', 77),
    ('Inter', 'Ange-Yoan Bonny', 'CF', 77),
    ('Inter', 'F. Pio Esposito', 'CF', 77),
    ('Inter', 'Andy Diouf', 'CMF', 75),
    ('Inter', 'Sebastiano Esposito', 'SS', 74),
    ('Inter', 'Franco Carboni', 'LB', 74),
    ('Inter', 'Petar Sučić', 'CMF', 73),
    ('Inter', 'Raffaele Di Gennaro', 'GK', 71),
    ('Inter', 'Giacomo De Pieri', 'RWF', 70),
    ('AC Milan', 'Rafael Leão', 'LWF', 85),
    ('AC Milan', 'Mike Maignan', 'GK', 84),
    ('AC Milan', 'Youssouf Fofana', 'DMF', 84),
    ('AC Milan', 'Adrien Rabiot', 'CMF', 84),
    ('AC Milan', 'Samuele Ricci', 'DMF', 83),
    ('AC Milan', 'Luka Modrić', 'CMF', 83),
    ('AC Milan', 'Christian Pulisic', 'RWF', 83),
    ('AC Milan', 'Christopher Nkunku', 'CF', 83),
    ('AC Milan', 'Santiago Gimenez', 'CF', 83),
    ('AC Milan', 'Fikayo Tomori', 'CB', 82),
    ('AC Milan', 'Pervis Estupiñán', 'LB', 82),
    ('AC Milan', 'Álvaro Morata', 'CF', 81),
    ('AC Milan', 'R. Loftus-Cheek', 'CMF', 81),
    ('AC Milan', 'A. Saelemaekers', 'RMF', 80),
    ('AC Milan', 'Davide Calabria', 'RB', 80),
    ('AC Milan', 'Samuel Chukwueze', 'RWF', 79),
    ('AC Milan', 'Strahinja Pavlović', 'CB', 79),
    ('AC Milan', 'Koni De Winter', 'CB', 79),
    ('AC Milan', 'Ismaël Bennacer', 'DMF', 79),
    ('AC Milan', 'Yunus Musah', 'CMF', 78),
    ('AC Milan', 'Pietro Terracciano', 'GK', 78),
    ('AC Milan', 'Ardon Jashari', 'DMF', 78),
    ('AC Milan', 'Tommaso Pobega', 'CMF', 77),
    ('AC Milan', 'Zachary Athekame', 'RB', 77),
    ('AC Milan', 'Matteo Gabbia', 'CB', 77),
    ('AC Milan', 'Francesco Camarda', 'CF', 73),
    ('AC Milan', 'Lorenzo Torriani', 'GK', 73),
    ('AC Milan', 'David Odogu', 'CB', 73),
    ('SSC Napoli', 'Kevin De Bruyne', 'AMF', 87),
    ('SSC Napoli', 'Scott McTominay', 'CMF', 85),
    ('SSC Napoli', 'Romelu Lukaku', 'CF', 84),
    ('SSC Napoli', 'Frank Anguissa', 'CMF', 84),
    ('SSC Napoli', 'A. Buongiorno', 'CB', 83),
    ('SSC Napoli', 'Giovanni Di Lorenzo', 'RB', 83),
    ('SSC Napoli', 'Stanislav Lobotka', 'DMF', 83),
    ('SSC Napoli', 'David Neres', 'RWF', 83),
    ('SSC Napoli', 'Alex Meret', 'GK', 82),
    ('SSC Napoli', 'Amir Rrahmani', 'CB', 82),
    ('SSC Napoli', 'Mathías Olivera', 'LB', 82),
    ('SSC Napoli', 'Sam Beukema', 'CB', 82),
    ('SSC Napoli', 'Miguel Gutiérrez', 'LB', 82),
    ('SSC Napoli', 'Matteo Politano', 'RWF', 82),
    ('SSC Napoli', 'Noa Lang', 'LWF', 82),
    ('SSC Napoli', 'Lorenzo Lucca', 'CF', 81),
    ('SSC Napoli', 'Giovanni Simeone', 'CF', 81),
    ('SSC Napoli', 'Billy Gilmour', 'DMF', 80),
    ('SSC Napoli', 'L. Spinazzola', 'LB', 79),
    ('SSC Napoli', 'Luca Marianucci', 'CB', 78),
    ('SSC Napoli', 'Alessandro Zanoli', 'RB', 78),
    ('SSC Napoli', 'Jesper Lindstrøm', 'RWF', 78),
    ('SSC Napoli', 'Jens Cajuste', 'DMF', 78),
    ('SSC Napoli', 'Michael Folorunsho', 'CMF', 77),
    ('SSC Napoli', 'Juan Jesus', 'CB', 77),
    ('SSC Napoli', 'Pasquale Mazzocchi', 'RB', 77),
    ('SSC Napoli', 'Cyril Ngonge', 'RWF', 77),
    ('SSC Napoli', 'Walid Cheddira', 'CF', 76),
    ('SSC Napoli', 'Alisson Santos', 'LWF', 75),
    ('SSC Napoli', 'Alessio Zerbin', 'LWF', 74),
    ('SSC Napoli', 'Nikita Contini', 'GK', 73),
    ('SSC Napoli', 'Giuseppe Ambrosino', 'CF', 73),
    ('SSC Napoli', 'Antonio Vergara', 'AMF', 72),
    ('SSC Napoli', 'Mathias Ferrante', 'GK', 71),
    ('SSC Napoli', 'Giovane', 'CF', 70),
    ('Atlético Madrid', 'Giuliano Simeone', 'RWF', 81),
    ('Atlético Madrid', 'Matteo Ruggeri', 'LB', 80),
    ('Atlético Madrid', 'Pablo Barrios', 'CMF', 80),
    ('Atlético Madrid', 'Clément Lenglet', 'CB', 80),
    ('Atlético Madrid', 'Thomas Lemar', 'AMF', 80),
    ('Atlético Madrid', 'Johnny Cardoso', 'CMF', 77),
    ('Atlético Madrid', 'Obed Vargas', 'CMF', 75),
    ('Atlético Madrid', 'Carlos Martín', 'LWF', 75),
    ('Atlético Madrid', 'Horatiu Moldovan', 'GK', 75),
    ('Atlético Madrid', 'Marc Pubill', 'CB', 73),
    ('Atlético Madrid', 'Rodrigo Mendoza', 'CMF', 71),
    ('Newcastle United', 'Sandro Tonali', 'CMF', 85),
    ('Newcastle United', 'Anthony Gordon', 'LWF', 85),
    ('Newcastle United', 'Sven Botman', 'CB', 84),
    ('Newcastle United', 'Bruno Guimarães', 'CMF', 84),
    ('Newcastle United', 'Fabian Schär', 'CB', 83),
    ('Newcastle United', 'Harvey Barnes', 'LWF', 83),
    ('Newcastle United', 'Nick Pope', 'GK', 83),
    ('Newcastle United', 'Joelinton', 'CMF', 83),
    ('Newcastle United', 'Kieran Trippier', 'RB', 82),
    ('Newcastle United', 'Joe Willock', 'CMF', 82),
    ('Newcastle United', 'Anthony Elanga', 'RWF', 81),
    ('Newcastle United', 'Yoane Wissa', 'CF', 81),
    ('Newcastle United', 'Dan Burn', 'CB', 81),
    ('Newcastle United', 'Lewis Hall', 'LB', 80),
    ('Newcastle United', 'Malick Thiaw', 'CB', 80),
    ('Newcastle United', 'Tino Livramento', 'RB', 80),
    ('Newcastle United', 'Jacob Ramsey', 'CMF', 80),
    ('Newcastle United', 'O. Vlachodimos', 'GK', 80),
    ('Newcastle United', 'Jacob Murphy', 'RWF', 79),
    ('Newcastle United', 'Nick Woltemade', 'CF', 79),
    ('Newcastle United', 'Matt Targett', 'LB', 79),
    ('Newcastle United', 'Emil Krafth', 'RB', 77),
    ('Newcastle United', 'Alex Murphy', 'LB', 75),
    ('Newcastle United', 'Mark Gillespie', 'GK', 74),
    ('Newcastle United', 'Lewis Miley', 'CMF', 74),
    ('Newcastle United', 'William Osula', 'CF', 72),
    ('Newcastle United', 'John Ruddy', 'GK', 71),
    ('Newcastle United', 'Antonio Cordero', 'LWF', 71),
    ('BVB Borussia Dortmund', 'Gregor Kobel', 'GK', 84),
    ('BVB Borussia Dortmund', 'Nico Schlotterbeck', 'CB', 84),
    ('BVB Borussia Dortmund', 'Serhou Guirassy', 'CF', 84),
    ('BVB Borussia Dortmund', 'Waldemar Anton', 'CB', 82),
    ('BVB Borussia Dortmund', 'Emre Can', 'DMF', 82),
    ('BVB Borussia Dortmund', 'Marcel Sabitzer', 'CMF', 82),
    ('BVB Borussia Dortmund', 'Julian Brandt', 'AMF', 82),
    ('BVB Borussia Dortmund', 'Karim Adeyemi', 'RWF', 82),
    ('BVB Borussia Dortmund', 'Niklas Süle', 'CB', 81),
    ('BVB Borussia Dortmund', 'Julian Ryerson', 'RB', 81),
    ('BVB Borussia Dortmund', 'Jobe Bellingham', 'CMF', 81),
    ('BVB Borussia Dortmund', 'Yan Couto', 'RB', 80),
    ('BVB Borussia Dortmund', 'Maximilian Beier', 'CF', 80),
    ('BVB Borussia Dortmund', 'Ramy Bensebaini', 'CB', 80),
    ('BVB Borussia Dortmund', 'Felix Nmecha', 'CMF', 80),
    ('BVB Borussia Dortmund', 'Salih Özcan', 'DMF', 79),
    ('BVB Borussia Dortmund', 'C. Chukwuemeka', 'CMF', 78),
    ('BVB Borussia Dortmund', 'Daniel Svensson', 'LB', 77),
    ('BVB Borussia Dortmund', 'Diant Ramaj', 'GK', 77),
    ('BVB Borussia Dortmund', 'Julien Duranville', 'LWF', 77),
    ('BVB Borussia Dortmund', 'Alexander Meyer', 'GK', 76),
    ('BVB Borussia Dortmund', 'Fábio Silva', 'CF', 76),
    ('BVB Borussia Dortmund', 'Cole Campbell', 'RWF', 74),
    ('BVB Borussia Dortmund', 'Patrick Drewes', 'GK', 73),
    ('BVB Borussia Dortmund', 'Silas Ostrzinski', 'GK', 71),
    ('BVB Borussia Dortmund', 'Filippo Mané', 'CB', 71),
    ('BVB Borussia Dortmund', 'Almugera Kabar', 'LB', 71),
    ('BVB Borussia Dortmund', 'Justin Lerma', 'AMF', 67),
    ('AS Roma', 'Artem Dovbyk', 'CF', 83),
    ('AS Roma', 'Paulo Dybala', 'SS', 83),
    ('AS Roma', 'Mile Svilar', 'GK', 82),
    ('AS Roma', 'Gianluca Mancini', 'CB', 82),
    ('AS Roma', 'Manu Koné', 'CMF', 82),
    ('AS Roma', 'Matías Soulé', 'RWF', 82),
    ('AS Roma', 'Lorenzo Pellegrini', 'AMF', 82),
    ('AS Roma', 'Evan Ndicka', 'CB', 81),
    ('AS Roma', 'Wesley França', 'RB', 81),
    ('AS Roma', 'Mario Hermoso', 'CB', 80),
    ('AS Roma', 'Niccolò Pisilli', 'CMF', 80),
    ('AS Roma', 'S. El Shaarawy', 'LWF', 80),
    ('AS Roma', 'Angeliño', 'LB', 80),
    ('AS Roma', 'Tommaso Baldanzi', 'AMF', 79),
    ('AS Roma', 'Zeki Çelik', 'RB', 79),
    ('AS Roma', 'Bryan Cristante', 'DMF', 79),
    ('AS Roma', 'Pierluigi Gollini', 'GK', 78),
    ('AS Roma', 'Neil El Aynaoui', 'CMF', 77),
    ('AS Roma', 'Anass Salah-Eddine', 'LB', 77),
    ('AS Roma', 'Eldor Shomurodov', 'CF', 77),
    ('AS Roma', 'Devis Vásquez', 'GK', 77),
    ('AS Roma', 'Marash Kumbulla', 'CB', 76),
    ('AS Roma', 'Saud Abdulhamid', 'RB', 76),
    ('AS Roma', 'Devyne Rensch', 'RB', 75),
    ('AS Roma', 'Jan Ziolkowski', 'CB', 74),
    ('AS Roma', 'Radoslaw Zelezny', 'GK', 73),
    ('AS Roma', 'Robinio Vaz', 'CF', 71),
    ('AS Roma', 'Buba Sangaré', 'RB', 71),

]

def run_update():
    all_db_players = list(Player.objects.select_related('team').all())
    used_db_ids = set()
    matched_updates = []
    unmatched = []

    for origin_team, p_name, p_pos, p_ovr in PLAYER_DATA:
        m_clean = clean_name(p_name)
        m_parts = m_clean.split()
        match = None

        # Priority 1: Match in original team if still there
        for dp in all_db_players:
            if dp.id in used_db_ids:
                continue
            if dp.team and dp.team.name == origin_team:
                d_clean = clean_name(dp.name)
                d_parts = d_clean.split()
                if d_clean == m_clean:
                    match = dp
                    break
                if len(m_parts) >= 2 and len(d_parts) >= 2:
                    if f"{m_parts[0][0]} {m_parts[-1]}" == f"{d_parts[0][0]} {d_parts[-1]}":
                        match = dp
                        break

        # Priority 2: Global Search (if player transferred to another team or has name alias)
        if not match:
            if m_clean == 'nico gonzalez':
                if origin_team == 'Juventus':
                    for dp in all_db_players:
                        if dp.id not in used_db_ids and clean_name(dp.name) in ['nico gonzalez', 'n gonzalez'] and (dp.position in ['LWF', 'RWF', 'LMF', 'RMF'] or (dp.team and dp.team.name == 'Juventus')):
                            match = dp
                            break
                elif origin_team == 'Manchester City':
                    for dp in all_db_players:
                        if dp.id not in used_db_ids and clean_name(dp.name) in ['nico gonzalez', 'n gonzalez'] and (dp.position in ['CMF', 'DMF'] or (dp.team and dp.team.name == 'Manchester City')):
                            match = dp
                            break
            else:
                for dp in all_db_players:
                    if dp.id in used_db_ids:
                        continue
                    d_clean = clean_name(dp.name)
                    d_parts = d_clean.split()
                    if d_clean == m_clean:
                        match = dp
                        break
                    if len(m_parts) >= 2 and len(d_parts) >= 2:
                        if f"{m_parts[0][0]} {m_parts[-1]}" == f"{d_parts[0][0]} {d_parts[-1]}":
                            match = dp
                            break

        if match:
            used_db_ids.add(match.id)
            matched_updates.append((match, p_pos, p_ovr))
        else:
            unmatched.append((origin_team, p_name, p_pos, p_ovr))

    print(f"Total target players: {len(PLAYER_DATA)}")
    print(f"Successfully matched: {len(matched_updates)}")
    print(f"Unmatched: {len(unmatched)}")

    with transaction.atomic():
        for dp, p_pos, p_ovr in matched_updates:
            dp.overall = p_ovr
            dp.base_overall = p_ovr
            dp.position = p_pos
            dp.rarity = calculate_rarity(p_ovr, dp.potential_ovr or p_ovr)
            dp.base_stamina = min(99, max(60, p_ovr + (3 if p_pos != 'GK' else 0)))
            dp.save(update_fields=['overall', 'base_overall', 'position', 'rarity', 'base_stamina'])

        # Recalculate team star ratings
        for team in Team.objects.all():
            team.update_star_rating()

    print("✅ All player stats updated and team star ratings recalculated successfully!")

if __name__ == '__main__':
    run_update()
