# Generated by Django 6.0.7 on 2026-08-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بسته')),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ دلار مجازی')),
                ('price_irr', models.PositiveIntegerField(help_text='قیمت بسته به تومان (Toman) که در درگاه استفاده می\u200cشود.', verbose_name='قیمت به تومان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بسته فروشگاه',
                'verbose_name_plural': 'بسته\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ دلار مجازی')),
                ('amount_irr', models.PositiveIntegerField(default=0, help_text='صفر برای تراکنش\u200cهای غیر پرداختی', verbose_name='مبلغ تراکنش به تومان')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'واریز/خرید بسته'), ('WITHDRAW', 'برداشت/هزینه'), ('PRIZE', 'جایزه مسابقات')], max_length=15, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق/لغو شده')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority زرین\u200cپال')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری زرین\u200cپال (RefID)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
