# Generated by Django 6.0.7 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount_usd',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مبلغ تراکنش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('BUDGET', 'بودجه باشگاه'), ('GEMS', 'جم')], default='BUDGET', max_length=10, verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MATCH_REWARD', 'پاداش بازی'), ('TRANSFER_BUY', 'خرید بازیکن'), ('TRANSFER_SELL', 'فروش بازیکن'), ('FACILITY_UPGRADE', 'ارتقای تسهیلات'), ('WAGE', 'پرداخت دستمزد'), ('STORE_PURCHASE', 'خرید بسته (پرداخت واقعی)'), ('GACHA_OPEN', 'باز کردن پک'), ('SEASON_PASS_REWARD', 'پاداش سیزن\u200cپس'), ('ADMIN_ADJUST', 'تنظیم دستی ادمین')], max_length=25, verbose_name='نوع تراکنش'),
        ),
    ]
