# Generated by Django 6.0.7 on 2026-08-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_remove_transaction_amount_usd_transaction_amount_and_more'),
        ('teams', '0016_alter_clubfacilities_academy_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='شماره کارت بانکی (مثال: 6037-9971-1234-5678)', max_length=19, verbose_name='شماره کارت')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('bank_name', models.CharField(blank=True, default='', max_length=50, verbose_name='نام بانک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات کارت بانکی',
                'verbose_name_plural': 'تنظیمات کارت بانکی',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_irr', models.PositiveIntegerField(verbose_name='مبلغ به تومان')),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='دلار مجازی')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='تصویر رسید')),
                ('status', models.CharField(choices=[('AWAITING_RECEIPT', 'در انتظار آپلود رسید'), ('PENDING_REVIEW', 'در انتظار بررسی ادمین'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='AWAITING_RECEIPT', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='economy.storepackage', verbose_name='بسته انتخابی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'درخواست پرداخت کارت به کارت',
                'verbose_name_plural': 'درخواست\u200cهای پرداخت کارت به کارت',
                'ordering': ['-created_at'],
            },
        ),
    ]
