# Generated by Django 6.0.7 on 2026-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_cardtocardsettings_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='currency_type',
            field=models.CharField(choices=[('BUDGET', 'دلار مجازی'), ('GEMS', 'الماس / جم')], default='GEMS', max_length=10, verbose_name='نوع ارز'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار ارز اعطایی'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='currency_type',
            field=models.CharField(choices=[('BUDGET', 'دلار مجازی'), ('GEMS', 'الماس / جم')], default='GEMS', max_length=10, verbose_name='نوع ارز اعطایی'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار ارز اعطایی'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='دلار مجازی (سازگاری)'),
        ),
        migrations.AlterField(
            model_name='storepackage',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مبلغ دلار مجازی (سازگاری)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MATCH_REWARD', 'پاداش بازی'), ('TRANSFER_BUY', 'خرید بازیکن'), ('TRANSFER_SELL', 'فروش بازیکن'), ('FACILITY_UPGRADE', 'ارتقای تسهیلات'), ('WAGE', 'پرداخت دستمزد'), ('STORE_PURCHASE', 'خرید بسته (پرداخت واقعی)'), ('GACHA_OPEN', 'باز کردن پک'), ('SEASON_PASS_REWARD', 'پاداش سیزن\u200cپس'), ('ADMIN_ADJUST', 'تنظیم دستی ادمین'), ('STAMINA_RECOVERY', 'ریکاوری استقامت بازیکن'), ('INJURY_HEAL', 'درمان فوری مصدومیت'), ('UNDERDOG_BONUS', 'پاداش شگفتی\u200cسازی مسابقه')], max_length=25, verbose_name='نوع تراکنش'),
        ),
    ]
