# Generated by Django 6.0.7 on 2026-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_paymentrequest_currency_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepackage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'بسته فروشگاه', 'verbose_name_plural': 'بسته\u200cهای فروشگاه'},
        ),
        migrations.AddField(
            model_name='storepackage',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار بونوس هدیه'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات بسته'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='icon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='کد آیکن یا تم'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
