# Generated by Django 6.0.7 on 2026-09-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_alter_storepackage_options_storepackage_bonus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار بونوس هدیه'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='badge_tag',
            field=models.CharField(blank=True, choices=[('', 'بدون برچسب'), ('HOT_DEAL', 'پیشنهاد شگفت\u200cانگیز 🔥'), ('BEST_SELLER', 'پرفروش\u200cترین ⭐'), ('SPECIAL', 'ویژه 💎'), ('BEST_VALUE', 'ارزش خرید بالا ⚡'), ('LIMITED', 'تخفیف محدود ⏳'), ('POPULAR', 'محبوب مربیان 🚀')], default='', max_length=50, verbose_name='برچسب رنگی بسته'),
        ),
    ]
