# Generated by Django 6.0.7 on 2026-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_paymentrequest_bonus_amount_storepackage_badge_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackage',
            name='custom_tag_color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='پالت رنگ تگ اختصاصی'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='custom_tag_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='متن تگ اختصاصی'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='discount_price_irr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف به تومان'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='discount_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پایان تخفیف ساعتی'),
        ),
    ]
