# Generated by Django 6.0.7 on 2026-09-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_storepackage_custom_tag_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MATCH_REWARD', 'پاداش بازی'), ('TRANSFER_BUY', 'خرید بازیکن'), ('TRANSFER_SELL', 'فروش بازیکن'), ('FACILITY_UPGRADE', 'ارتقای تسهیلات'), ('WAGE', 'پرداخت دستمزد'), ('STORE_PURCHASE', 'خرید بسته (پرداخت واقعی)'), ('GACHA_OPEN', 'باز کردن پک'), ('SEASON_PASS_REWARD', 'پاداش سیزن\u200cپس'), ('ADMIN_ADJUST', 'تنظیم دستی ادمین'), ('STAMINA_RECOVERY', 'ریکاوری استقامت بازیکن'), ('INJURY_HEAL', 'درمان فوری مصدومیت'), ('UNDERDOG_BONUS', 'پاداش شگفتی\u200cسازی مسابقه'), ('AIRDROP_REWARD', 'پاداش و ایردراپ همگانی')], max_length=25, verbose_name='نوع تراکنش'),
        ),
        migrations.CreateModel(
            name='MassRewardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پاداش')),
                ('message', models.TextField(blank=True, default='', verbose_name='پیام و متن اعلان')),
                ('gems_amount', models.PositiveIntegerField(default=0, verbose_name='تعداد جم اهدایی به هر تیم')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مبلغ دلار اهدایی به هر تیم')),
                ('teams_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تیم\u200cهای دریافت\u200cکننده')),
                ('target_type', models.CharField(choices=[('ALL', 'همه تیم\u200cها'), ('SELECTED', 'تیم\u200cهای منتخب')], default='ALL', max_length=20, verbose_name='نوع جامعه هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اعطا')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_rewards', to=settings.AUTH_USER_MODEL, verbose_name='ادمین واریزکننده')),
            ],
            options={
                'verbose_name': 'ایردراپ و پاداش همگانی',
                'verbose_name_plural': 'ایردراپ\u200cها و پاداش\u200cهای همگانی',
                'ordering': ['-created_at'],
            },
        ),
    ]
