# Generated by Django 6.0.7 on 2026-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_alter_transaction_transaction_type_massrewardgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('MATCH_REWARD', 'پاداش بازی'), ('TRANSFER_BUY', 'خرید بازیکن'), ('TRANSFER_SELL', 'فروش بازیکن'), ('FACILITY_UPGRADE', 'ارتقای تسهیلات'), ('WAGE', 'پرداخت دستمزد'), ('STORE_PURCHASE', 'خرید بسته (پرداخت واقعی)'), ('GACHA_OPEN', 'باز کردن پک'), ('SEASON_PASS_REWARD', 'پاداش سیزن\u200cپس'), ('ADMIN_ADJUST', 'تنظیم دستی ادمین'), ('STAMINA_RECOVERY', 'ریکاوری استقامت بازیکن'), ('INJURY_HEAL', 'درمان فوری مصدومیت'), ('UNDERDOG_BONUS', 'پاداش شگفتی\u200cسازی مسابقه'), ('AIRDROP_REWARD', 'پاداش و ایردراپ همگانی'), ('DISCIPLINARY_FINE', 'جریمه کمیته انضباطی'), ('DISCIPLINARY_REFUND', 'استرداد جریمه انضباطی')], max_length=25, verbose_name='نوع تراکنش'),
        ),
    ]
