# Generated by Django 6.0.7 on 2026-08-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='گل\u200cهای میزبان')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='گل\u200cهای میهمان')),
                ('date', models.DateTimeField(verbose_name='تاریخ و ساعت برگزاری')),
                ('status', models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی شده'), ('LIVE', 'در حال برگزاری'), ('FINISHED', 'پایان یافته')], default='SCHEDULED', max_length=15, verbose_name='وضعیت بازی')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='تیم میهمان')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='تیم میزبان')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'گل'), ('ASSIST', 'پاس گل'), ('YELLOW', 'کارت زرد'), ('RED', 'کارت قرمز'), ('SUB_IN', 'تعویض (ورود)'), ('SUB_OUT', 'تعویض (خروج)'), ('INJURY', 'مصدومیت')], max_length=10, verbose_name='نوع اتفاق')),
                ('minute', models.PositiveIntegerField(verbose_name='دقیقه')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='مسابقه')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='teams.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'اتفاق بازی',
                'verbose_name_plural': 'اتفاقات بازی',
            },
        ),
    ]
