# Generated by Django 6.0.7 on 2026-08-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0002_player_consecutive_games_player_injury_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fatigue_applied',
            field=models.BooleanField(default=False, help_text='آیا فرمول خستگی روی بازیکنان این مسابقه اعمال شده است؟', verbose_name='خستگی اعمال شده؟'),
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveIntegerField(default=0, help_text='تعداد دقایقی که بازیکن در زمین بوده (0-90)', verbose_name='دقایق بازی')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='نمره عملکرد بازیکن در این مسابقه (برای محاسبه رشد/افت)', max_digits=3, null=True, verbose_name='نمره بازیکن (0-10)')),
                ('was_starter', models.BooleanField(default=False, verbose_name='بازیکن اصلی بود؟')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match', verbose_name='مسابقه')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='teams.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'آمار بازیکن در مسابقه',
                'verbose_name_plural': 'آمار بازیکنان در مسابقات',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
