# Generated by Django 6.0.7 on 2026-08-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_fatigue_applied_playermatchstat'),
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تورنمنت')),
                ('tournament_type', models.CharField(choices=[('LEAGUE', 'لیگ'), ('CUP', 'جام حذفی')], default='LEAGUE', max_length=10, verbose_name='نوع مسابقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تورنمنت',
                'verbose_name_plural': 'تورنمنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='پنالتی\u200cهای میهمان'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='پنالتی\u200cهای میزبان'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_knockout',
            field=models.BooleanField(default=False, verbose_name='مسابقه حذفی است؟'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='matches.match', verbose_name='بازی بعدی (براکت)'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, help_text='مثال: هفته ۱، یک\u200cچهارم نهایی', max_length=50, verbose_name='مرحله/هفته'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='تیم میهمان'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت برگزاری'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='تیم میزبان'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.tournament', verbose_name='تورنمنت'),
        ),
    ]
