# Generated by Django 6.0.7 on 2026-08-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tournament_match_away_penalties_match_home_penalties_and_more'),
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSubstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='دقیقه درخواستی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی ادمین'), ('APPLIED', 'اعمال شده در بازی'), ('REJECTED', 'رد شده (غیرمجاز)')], default='PENDING', max_length=15, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='matches.match', verbose_name='مسابقه')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_in_requests', to='teams.player', verbose_name='بازیکن ورودی')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_out_requests', to='teams.player', verbose_name='بازیکن خروجی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'درخواست تعویض زنده',
                'verbose_name_plural': 'درخواست\u200cهای تعویض زنده',
                'ordering': ['-created_at'],
            },
        ),
    ]
