# Generated by Django 6.0.7 on 2026-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_livesubstitutionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='importance_multiplier',
            field=models.FloatField(default=1.0, help_text='ضریب اهمیت مسابقه (دربی، فینال و غیره)', verbose_name='ضریب اهمیت بازی'),
        ),
    ]
