# Generated by Django 6.0.7 on 2026-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_importance_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='half_status',
            field=models.CharField(choices=[('1ST_HALF', 'نیمه اول'), ('HALF_TIME', 'بین دو نیمه'), ('2ND_HALF', 'نیمه دوم'), ('EXTRA_TIME', 'وقت اضافه'), ('PENALTIES', 'ضربات پنالتی'), ('FINISHED', 'پایان بازی')], default='1ST_HALF', max_length=15, verbose_name='وضعیت نیمه'),
        ),
    ]
