# Generated by Django 6.0.7 on 2026-08-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_half_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='standings_processed',
            field=models.BooleanField(default=False, help_text='آیا این بازی در جدول رده\u200cبندی ثبت و محاسبه شده است؟', verbose_name='جدول پردازش شده؟'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='matches.season', verbose_name='فصل'),
        ),
    ]
