# Generated by Django 6.0.7 on 2026-08-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_season_match_standings_processed_tournament_season'),
        ('teams', '0011_team_gems'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0, verbose_name='بازی\u200cکرده')),
                ('won', models.PositiveIntegerField(default=0, verbose_name='برد')),
                ('drawn', models.PositiveIntegerField(default=0, verbose_name='مساوی')),
                ('lost', models.PositiveIntegerField(default=0, verbose_name='باخت')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='گل زده')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='گل خورده')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='teams.team', verbose_name='تیم')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.tournament', verbose_name='تورنمنت')),
            ],
            options={
                'verbose_name': 'جدول لیگ',
                'verbose_name_plural': 'جداول لیگ',
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='MatchTeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_percent', models.PositiveIntegerField(default=50, verbose_name='تسلط بر توپ (%)')),
                ('shots', models.PositiveIntegerField(default=0, verbose_name='ضربات')),
                ('shots_on_target', models.PositiveIntegerField(default=0, verbose_name='ضربات به هدف')),
                ('corners', models.PositiveIntegerField(default=0, verbose_name='کرنر')),
                ('fouls', models.PositiveIntegerField(default=0, verbose_name='خطا')),
                ('offsides', models.PositiveIntegerField(default=0, verbose_name='آفساید')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='matches.match', verbose_name='مسابقه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_match_stats', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'آمار تیمی مسابقه',
                'verbose_name_plural': 'آمارهای تیمی مسابقات',
                'unique_together': {('match', 'team')},
            },
        ),
    ]
