# Generated by Django 6.0.7 on 2026-08-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_leaguestanding_matchteamstat'),
        ('teams', '0016_alter_clubfacilities_academy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.PositiveIntegerField(default=0, verbose_name='دقیقه فعلی بازی'),
        ),
        migrations.AddField(
            model_name='match',
            name='stoppage_time',
            field=models.PositiveIntegerField(default=0, verbose_name='وقت اضافه نیمه (دقیقه)'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_events', to='teams.player', verbose_name='بازیکن پاسور'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='توضیحات تکمیلی رویداد'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='is_undone',
            field=models.BooleanField(default=False, verbose_name='باطل شده (Undo)'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='teams.team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='saves',
            field=models.PositiveIntegerField(default=0, verbose_name='مهارها (سیو دروازه\u200cبان)'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'گل'), ('ASSIST', 'پاس گل'), ('OWN_GOAL', 'گل به خودی'), ('PENALTY_SCORED', 'گل از روی نقطه پنالتی'), ('PENALTY_MISSED', 'پنالتی از دست رفته'), ('YELLOW', 'کارت زرد'), ('SECOND_YELLOW', 'کارت زرد دوم -> قرمز'), ('RED', 'کارت قرمز مستقیم'), ('SUB_IN', 'تعویض (ورود)'), ('SUB_OUT', 'تعویض (خروج)'), ('INJURY', 'مصدومیت'), ('VAR', 'بررسی VAR')], max_length=20, verbose_name='نوع اتفاق'),
        ),
    ]
