# Generated by Django 6.0.7 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_current_minute_match_stoppage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_url',
            field=models.URLField(blank=True, default='', help_text='لینک پخش زنده آپارات یا یوتیوب', max_length=500, verbose_name='لینک استریم زنده'),
        ),
    ]
