# Generated by Django 6.0.7 on 2026-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_stream_url'),
        ('teams', '0022_player_base_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ و ساعت برگزاری'),
        ),
        migrations.AlterField(
            model_name='match',
            name='half_status',
            field=models.CharField(choices=[('NOT_STARTED', 'شروع نشده'), ('1ST_HALF', 'نیمه اول'), ('HALF_TIME', 'بین دو نیمه'), ('2ND_HALF', 'نیمه دوم'), ('EXTRA_TIME', 'وقت اضافه'), ('PENALTIES', 'ضربات پنالتی'), ('FINISHED', 'پایان بازی')], db_index=True, default='NOT_STARTED', max_length=15, verbose_name='وضعیت نیمه'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: هفته ۱، یک\u200cچهارم نهایی', max_length=50, verbose_name='مرحله/هفته'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی شده'), ('LIVE', 'در حال برگزاری'), ('FINISHED', 'پایان یافته')], db_index=True, default='SCHEDULED', max_length=15, verbose_name='وضعیت بازی'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'status'], name='matches_mat_tournam_bfa07e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_name'], name='matches_mat_tournam_adc60f_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date', 'status'], name='matches_mat_date_bb0d17_idx'),
        ),
    ]
