# Generated by Django 6.0.7 on 2026-08-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_match_date_alter_match_half_status_and_more'),
        ('teams', '0022_player_base_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGamePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(default='4-3-3', max_length=20, verbose_name='سیستم ترکیب')),
                ('attacking_style', models.CharField(default='بازی مالکانه', max_length=50)),
                ('build_up', models.CharField(default='پاس کوتاه', max_length=50)),
                ('attacking_area', models.CharField(default='مرکز', max_length=20)),
                ('positioning', models.CharField(default='حفظ ترکیب', max_length=20)),
                ('support_range', models.PositiveIntegerField(default=7)),
                ('defensive_style', models.CharField(default='فشار خط مقدم', max_length=50)),
                ('containment_area', models.CharField(default='میانه', max_length=20)),
                ('pressing', models.CharField(default='تهاجمی', max_length=20)),
                ('defensive_line', models.PositiveIntegerField(default=6)),
                ('compactness', models.PositiveIntegerField(default=5)),
                ('adv_offense_1', models.CharField(default='هیچکدام', max_length=50)),
                ('adv_offense_2', models.CharField(default='هیچکدام', max_length=50)),
                ('adv_defense_1', models.CharField(default='هیچکدام', max_length=50)),
                ('adv_defense_2', models.CharField(default='هیچکدام', max_length=50)),
                ('is_submitted', models.BooleanField(db_index=True, default=False, verbose_name='تایید و ارسال شده برای این مسابقه')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت و ارسال')),
                ('players_data', models.JSONField(blank=True, default=list, verbose_name='چیدمان بازیکنان در این مسابقه')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplans', to='matches.match', verbose_name='مسابقه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_gameplans', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'ترکیب و تاکتیک مسابقه',
                'verbose_name_plural': 'ترکیب\u200cها و تاکتیک\u200cهای مسابقات',
                'indexes': [models.Index(fields=['match', 'team', 'is_submitted'], name='matches_mat_match_i_b95231_idx')],
                'unique_together': {('match', 'team')},
            },
        ),
    ]
