# Generated by Django 6.0.7 on 2026-08-21 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_matchgameplan'),
        ('teams', '0022_player_base_overall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'گل'), ('ASSIST', 'پاس گل'), ('OWN_GOAL', 'گل به خودی'), ('PENALTY_SCORED', 'گل از روی نقطه پنالتی'), ('PENALTY_MISSED', 'پنالتی از دست رفته'), ('YELLOW', 'کارت زرد'), ('SECOND_YELLOW', 'کارت زرد دوم -> قرمز'), ('RED', 'کارت قرمز مستقیم'), ('SUB_IN', 'تعویض (ورود)'), ('SUB_OUT', 'تعویض (خروج)'), ('INJURY', 'مصدومیت'), ('VAR', 'بررسی VAR'), ('UNDO_GOAL', 'لغو گل'), ('UNDO_EVENT', 'لغو رویداد'), ('INFO', 'پیام اطلاعاتی')], max_length=20, verbose_name='نوع اتفاق'),
        ),
        migrations.CreateModel(
            name='LiveInGameChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_category', models.CharField(choices=[('SUBSTITUTION', 'تعویض بازیکن'), ('POSITION', 'جابجایی و تغییر پست'), ('TACTIC', 'تغییر تاکتیک'), ('FORMATION', 'تغییر سیستم بازی')], default='TACTIC', max_length=20, verbose_name='دسته\u200cبندی تغییر')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان تغییر')),
                ('detail', models.TextField(verbose_name='جزئیات تغییر')),
                ('diff_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای تفاوت (Payload)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی داور'), ('APPLIED', 'تایید و اعمال شده ✓'), ('REJECTED', 'رد شده ✗')], default='PENDING', max_length=15, verbose_name='وضعیت درخواست')),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='دقیقه ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اعمال داور')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_in_game_changes', to=settings.AUTH_USER_MODEL, verbose_name='سرمربی')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_game_changes', to='matches.match', verbose_name='مسابقه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_game_changes', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'تغییر حین بازی مربی',
                'verbose_name_plural': 'تغییرات حین بازی مربیان',
                'ordering': ['-created_at'],
            },
        ),
    ]
