# Generated by Django 6.0.7 on 2026-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_matchgameplan_preset_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='is_manually_overridden',
            field=models.BooleanField(default=False, verbose_name='ویرایش دستی شده توسط ادمین'),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points_deduction',
            field=models.PositiveIntegerField(default=0, verbose_name='کسر امتیاز جریمه'),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points_deduction_reason',
            field=models.TextField(blank=True, default='', verbose_name='علت کسر امتیاز'),
        ),
    ]
