# Generated by Django 6.0.7 on 2026-09-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_leaguestanding_is_manually_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_round',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره دور در براکت'),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(blank=True, choices=[('', 'بدون براکت'), ('WINNERS', 'براکت برنده\u200cها'), ('LOSERS', 'براکت بازنده\u200cها'), ('GRAND_FINAL', 'فینال بزرگ')], db_index=True, default='', max_length=15, verbose_name='سمت براکت'),
        ),
        migrations.AddField(
            model_name='match',
            name='has_extra_time',
            field=models.BooleanField(default=False, help_text='فقط برای مراحل پایانی (LB-R3+, WB Semi+)', verbose_name='وقت اضافه فعال؟'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_reset_match',
            field=models.BooleanField(default=False, verbose_name='بازی ریست فینال بزرگ؟'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_previous_matches', to='matches.match', verbose_name='بازی بعدی بازنده (براکت بازنده\u200cها)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('LEAGUE', 'لیگ'), ('CUP', 'جام حذفی'), ('BATTLE_ROYALE', 'نبرد رویال')], default='LEAGUE', max_length=20, verbose_name='نوع مسابقات'),
        ),
    ]
