# Generated by Django 6.0.7 on 2026-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_match_bracket_round_match_bracket_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamstat',
            name='crosses',
            field=models.PositiveIntegerField(default=0, verbose_name='سانتر'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='free_kicks',
            field=models.PositiveIntegerField(default=0, verbose_name='ضربه آزاد'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='interceptions',
            field=models.PositiveIntegerField(default=0, verbose_name='سد توپ'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='passes',
            field=models.PositiveIntegerField(default=0, verbose_name='پاس کل'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='passes_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='پاس موفق'),
        ),
        migrations.AddField(
            model_name='matchteamstat',
            name='tackles',
            field=models.PositiveIntegerField(default=0, verbose_name='تکل'),
        ),
    ]
