# Generated by Django 6.0.7 on 2026-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_matchteamstat_crosses_matchteamstat_free_kicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_attitude_level',
            field=models.IntegerField(default=0, verbose_name='فاز تاکتیکی میهمان (-1 دفاعی، 0 متعادل، 1 هجومی، 2 تمام\u200cتهاجمی)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_attitude_level',
            field=models.IntegerField(default=0, verbose_name='فاز تاکتیکی میزبان (-1 دفاعی، 0 متعادل، 1 هجومی، 2 تمام\u200cتهاجمی)'),
        ),
    ]
