# Generated by Django 6.0.7 on 2026-08-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0011_team_gems'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('xp_required', models.PositiveIntegerField()),
                ('free_reward_gems', models.PositiveIntegerField(default=0)),
                ('vip_reward_gems', models.PositiveIntegerField(default=0)),
                ('vip_reward_player_rarity', models.CharField(blank=True, max_length=20)),
                ('is_final_level', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تسک')),
                ('task_type', models.CharField(choices=[('WIN_MATCHES', 'برد در N بازی'), ('SCORE_GOALS', 'گلزنی'), ('SUBMIT_LINEUP', 'ثبت ترکیب به\u200cموقع'), ('OPEN_PACKS', 'باز کردن پک'), ('CLEAN_SHEETS', 'کلین\u200cشیت')], max_length=20)),
                ('target_value', models.PositiveIntegerField(verbose_name='هدف عددی')),
                ('reward_xp', models.PositiveIntegerField(default=50, verbose_name='امتیاز XP پاس فصلی')),
                ('week_number', models.PositiveIntegerField(verbose_name='شماره هفته فعال\u200cبودن')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'تسک هفتگی',
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('is_vip', models.BooleanField(default=False)),
                ('claimed_levels', models.JSONField(default=list)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_pass', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='teams.team')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_pass.weeklytask')),
            ],
            options={
                'unique_together': {('team', 'task')},
            },
        ),
    ]
