# Generated by Django 6.0.7 on 2026-08-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_pass', '0001_initial'),
        ('teams', '0022_player_base_overall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonpasslevel',
            options={'ordering': ['level'], 'verbose_name': 'سطح سیزن پس', 'verbose_name_plural': 'سطوح سیزن پس'},
        ),
        migrations.AlterModelOptions(
            name='teamseasonpass',
            options={'verbose_name': 'سیزن پس تیم', 'verbose_name_plural': 'سیزن پس تیم\u200cها'},
        ),
        migrations.AddField(
            model_name='seasonpasslevel',
            name='free_reward_coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='پاداش دلاری رایگان'),
        ),
        migrations.AddField(
            model_name='seasonpasslevel',
            name='reward_title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='عنوان پاداش'),
        ),
        migrations.AddField(
            model_name='seasonpasslevel',
            name='vip_reward_coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='پاداش دلاری VIP'),
        ),
        migrations.AddField(
            model_name='teamseasonpass',
            name='assigned_legend_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_pass_assigned_team', to='teams.player', verbose_name='بازیکن لجند اختصاصی تیم'),
        ),
        migrations.AddField(
            model_name='teamseasonpass',
            name='legend_claimed',
            field=models.BooleanField(default=False, verbose_name='لجند دریافت شده است؟'),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='free_reward_gems',
            field=models.PositiveIntegerField(default=0, verbose_name='پاداش جم رایگان'),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='is_final_level',
            field=models.BooleanField(default=False, verbose_name='سطح نهایی (پاداش لجند)'),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='level',
            field=models.PositiveIntegerField(unique=True, verbose_name='شماره سطح'),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='vip_reward_gems',
            field=models.PositiveIntegerField(default=0, verbose_name='پاداش جم VIP'),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='vip_reward_player_rarity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonpasslevel',
            name='xp_required',
            field=models.PositiveIntegerField(verbose_name='XP مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='teamseasonpass',
            name='claimed_levels',
            field=models.JSONField(default=list, verbose_name='سطوح دریافت شده'),
        ),
        migrations.AlterField(
            model_name='teamseasonpass',
            name='current_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح فعلی'),
        ),
        migrations.AlterField(
            model_name='teamseasonpass',
            name='current_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='XP فعلی'),
        ),
        migrations.AlterField(
            model_name='teamseasonpass',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='عضویت VIP'),
        ),
        migrations.AlterField(
            model_name='teamseasonpass',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_pass', to='teams.team', verbose_name='تیم'),
        ),
    ]
