# Generated by Django 6.0.7 on 2026-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season_pass', '0002_alter_seasonpasslevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonpass',
            name='claimed_vip_levels',
            field=models.JSONField(blank=True, default=list, verbose_name='سطوح VIP دریافت شده'),
        ),
    ]
