# Generated by Django 6.0.7 on 2026-08-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ معامله')),
                ('transfer_type', models.CharField(max_length=20, verbose_name='نوع انتقال')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتقال')),
                ('buyer_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_history', to='teams.team', verbose_name='تیم خریدار')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history', to='teams.player', verbose_name='بازیکن')),
                ('seller_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_history', to='teams.team', verbose_name='تیم فروشنده')),
            ],
            options={
                'verbose_name': 'تاریخچه نقل و انتقال',
                'verbose_name_plural': 'تاریخچه نقل و انتقالات',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('FIXED_PRICE', 'قیمت مقطوع'), ('AUCTION', 'مزایده')], default='FIXED_PRICE', max_length=15, verbose_name='نوع فروش')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت فروش / قیمت پایه مزایده')),
                ('highest_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='بالاترین پیشنهاد')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('SOLD', 'فروخته شده'), ('CANCELLED', 'لغو شده'), ('EXPIRED', 'منقضی شده')], default='ACTIVE', max_length=15, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_won', to='teams.team', verbose_name='بالاترین پیشنهاددهنده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to='teams.player', verbose_name='بازیکن')),
                ('seller_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_sold', to='teams.team', verbose_name='تیم فروشنده')),
            ],
            options={
                'verbose_name': 'آگهی نقل و انتقال',
                'verbose_name_plural': 'آگهی\u200cهای نقل و انتقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پیشنهاد (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت پیشنهاد')),
                ('bidder_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_made', to='teams.team', verbose_name='تیم پیشنهاددهنده')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='transfers.transferlisting', verbose_name='آگهی مربوطه')),
            ],
            options={
                'verbose_name': 'پیشنهاد مزایده',
                'verbose_name_plural': 'پیشنهادهای مزایده',
                'ordering': ['-amount_usd'],
            },
        ),
    ]
