# Generated by Django 6.0.7 on 2026-08-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_default_formation'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('DIRECT_TRANSFER', 'خرید قطعی'), ('SWAP', 'معاوضه'), ('LOAN', 'قرضی')], default='DIRECT_TRANSFER', max_length=20, verbose_name='نوع پیشنهاد')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مبلغ نقدی (USD)')),
                ('loan_duration_matches', models.PositiveIntegerField(default=0, verbose_name='مدت قرارداد قرضی (تعداد بازی)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('ACCEPTED', 'قبول شده'), ('REJECTED', 'رد شده'), ('COUNTERED', 'پیشنهاد متقابل'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت پیشنهاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('parent_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='transfers.transferoffer', verbose_name='پیشنهاد مرجع (برای مذاکره متقابل)')),
                ('receiver_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to='teams.team', verbose_name='تیم دریافت کننده')),
                ('sender_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to='teams.team', verbose_name='تیم پیشنهاد دهنده')),
                ('swap_players', models.ManyToManyField(blank=True, related_name='swap_offers_involved', to='teams.player', verbose_name='بازیکنان پیشنهادی برای معاوضه')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to='teams.player', verbose_name='بازیکن هدف')),
            ],
            options={
                'verbose_name': 'پیشنهاد نقل و انتقال',
                'verbose_name_plural': 'پیشنهادهای نقل و انتقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OFFER_MADE', 'ثبت پیشنهاد اولیه'), ('COUNTER_OFFER', 'پیشنهاد متقابل'), ('OFFER_REJECTED', 'رد پیشنهاد'), ('TRANSFER_FINALIZED', 'تکمیل انتقال'), ('PLAYER_RELEASED', 'فسخ قرارداد بازیکن')], max_length=30, verbose_name='نوع رویداد')),
                ('description', models.TextField(verbose_name='شرح رویداد')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان رویداد')),
                ('related_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='transfers.transferoffer', verbose_name='پیشنهاد مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ نقل و انتقال',
                'verbose_name_plural': 'لاگ\u200cهای نقل و انتقالات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
