# Generated by Django 6.0.7 on 2026-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transferoffer_transferlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('ACCEPTED', 'قبول شده'), ('REJECTED', 'رد شده'), ('COUNTERED', 'پیشنهاد متقابل'), ('SUPERSEDED', 'جایگزین شده با پیشنهاد جدید'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=15, verbose_name='وضعیت'),
        ),
    ]
