# Generated by Django 6.0.7 on 2026-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_alter_transferoffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlog',
            name='event_type',
            field=models.CharField(choices=[('OFFER_MADE', 'ثبت پیشنهاد اولیه'), ('COUNTER_OFFER', 'پیشنهاد متقابل'), ('OFFER_REJECTED', 'رد پیشنهاد'), ('OFFER_CANCELLED', 'لغو پیشنهاد'), ('TRANSFER_FINALIZED', 'تکمیل انتقال'), ('PLAYER_RELEASED', 'فسخ قرارداد بازیکن'), ('LOAN_EXPIRED', 'پایان قرارداد قرضی'), ('FREE_AGENT_SIGNED', 'جذب بازیکن آزاد')], max_length=30, verbose_name='نوع رویداد'),
        ),
    ]
