# Generated by Django 6.0.7 on 2026-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_alter_transferlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlog',
            name='event_type',
            field=models.CharField(choices=[('OFFER_MADE', 'ثبت پیشنهاد اولیه'), ('COUNTER_OFFER', 'پیشنهاد متقابل'), ('OFFER_REJECTED', 'رد پیشنهاد'), ('OFFER_CANCELLED', 'لغو پیشنهاد'), ('TRANSFER_FINALIZED', 'تکمیل انتقال'), ('PLAYER_RELEASED', 'فسخ قرارداد بازیکن'), ('LOAN_EXPIRED', 'پایان قرارداد قرضی'), ('FREE_AGENT_SIGNED', 'جذب بازیکن آزاد'), ('ADMIN_ROLLBACK', 'ابطال اضطراری توسط ادمین')], max_length=30, verbose_name='نوع رویداد'),
        ),
    ]
