# Generated by Django 6.0.7 on 2026-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_alter_transferlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferoffer',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='پیام یا یادداشت مربی فرستنده'),
        ),
        migrations.AddField(
            model_name='transferoffer',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='دلیل یا یادداشت رد پیشنهاد'),
        ),
    ]
