# Generated by Django 6.0.7 on 2026-08-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پک')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پک به دلار مجازی')),
                ('rate_rare', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='شانس Rare (%)')),
                ('rate_epic', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='شانس Epic (%)')),
                ('rate_legendary', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='شانس Legendary (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پک گاشا',
                'verbose_name_plural': 'پک\u200cهای گاشا',
            },
        ),
        migrations.CreateModel(
            name='GachaPity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='شمارنده Pity (تعداد پک بدون Legendary)')),
                ('total_pulls', models.PositiveIntegerField(default=0, verbose_name='کل پک\u200cهای باز شده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gacha_pity', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'شمارنده Pity تیم',
                'verbose_name_plural': 'شمارنده\u200cهای Pity تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PackOpeningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_drawn', models.CharField(choices=[('RARE', 'Rare (OVR 70-79)'), ('EPIC', 'Epic (OVR 80-86)'), ('LEGENDARY', 'Legendary (OVR 87+)')], max_length=15, verbose_name='درجه ناداری')),
                ('pity_applied', models.BooleanField(default=False, verbose_name='از سیستم Pity استفاده شد؟')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازکردن')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gacha.gachapack', verbose_name='پک باز شده')),
                ('player_obtained', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obtained_from_packs', to='teams.player', verbose_name='بازیکن بدست آمده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_logs', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'تاریخچه بازکردن پک',
                'verbose_name_plural': 'تاریخچه بازکردن پک\u200cها',
                'ordering': ['-opened_at'],
            },
        ),
    ]
