# Generated by Django 6.0.7 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gachapity',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='packopeninglog',
            name='cost_usd',
        ),
        migrations.AddField(
            model_name='gachapack',
            name='cost_gems',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت به جم'),
        ),
        migrations.AddField(
            model_name='gachapack',
            name='cost_irr',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت به تومان (خرید مستقیم)'),
        ),
        migrations.AddField(
            model_name='gachapack',
            name='purchase_method',
            field=models.CharField(choices=[('GEMS', 'فقط جم'), ('DIRECT', 'فقط پرداخت مستقیم'), ('BOTH', 'هر دو روش')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='gachapity',
            name='counter_direct',
            field=models.PositiveIntegerField(default=0, verbose_name='شمارنده پرداخت مستقیم'),
        ),
        migrations.AddField(
            model_name='gachapity',
            name='counter_gems',
            field=models.PositiveIntegerField(default=0, verbose_name='شمارنده جم (تعداد پک بدون Legendary)'),
        ),
        migrations.AddField(
            model_name='packopeninglog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AddField(
            model_name='packopeninglog',
            name='payment_method',
            field=models.CharField(choices=[('GEMS', 'جم'), ('DIRECT', 'مستقیم')], default='GEMS', max_length=10, verbose_name='روش پرداخت'),
        ),
    ]
