# Generated by Django 6.0.7 on 2026-08-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0002_remove_gachapity_counter_and_more'),
        ('teams', '0022_player_base_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پک')),
                ('tier', models.CharField(choices=[('BRONZE', 'برنز'), ('SILVER', 'نقره'), ('LEGENDARY', 'لجندری')], default='BRONZE', max_length=20, verbose_name='سطح / تیر')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packs/covers/', verbose_name='تصویر کاور پک')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات پک')),
                ('ovr_range_text', models.CharField(blank=True, default='', help_text='مثال: OVR 85-90 یا بازیکنان منتخب هفته', max_length=50, verbose_name='محدوده اورال (نمایشی)')),
                ('cost_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت به دلار مجازی')),
                ('cost_gems', models.PositiveIntegerField(default=0, verbose_name='قیمت به جم')),
                ('cost_irr', models.PositiveIntegerField(default=0, verbose_name='قیمت به تومان (خرید مستقیم)')),
                ('purchase_method', models.CharField(choices=[('GEMS', 'فقط جم'), ('DIRECT', 'فقط پرداخت مستقیم / دلار'), ('BOTH', 'هر دو روش')], default='BOTH', max_length=10, verbose_name='روش خرید مجاز')),
                ('featured_team', models.CharField(blank=True, default='', help_text='مثلاً: اسطوره\u200cهای میلان یا آرسنال کلاسیک', max_length=100, verbose_name='تیم منتخب (پک لجندری/تیمی)')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='شروع در دسترس بودن')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان در دسترس بودن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پک بازیکنان',
                'verbose_name_plural': 'پک\u200cهای بازیکنان',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='packopeninglog',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='gachapity',
            name='team',
        ),
        migrations.RemoveField(
            model_name='packopeninglog',
            name='player_obtained',
        ),
        migrations.RemoveField(
            model_name='packopeninglog',
            name='team',
        ),
        migrations.CreateModel(
            name='PackPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بازیکن')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('DMF', 'Defensive Midfielder'), ('CMF', 'Central Midfielder'), ('LMF', 'Left Midfielder'), ('RMF', 'Right Midfielder'), ('AMF', 'Attacking Midfielder'), ('LWF', 'Left Wing Forward'), ('RWF', 'Right Wing Forward'), ('SS', 'Second Striker'), ('CF', 'Center Forward')], max_length=3, verbose_name='پست')),
                ('overall', models.PositiveIntegerField(verbose_name='اورال (OVR)')),
                ('potential_ovr', models.PositiveIntegerField(default=99, verbose_name='سقف پتانسیل')),
                ('age', models.PositiveIntegerField(default=22, verbose_name='سن')),
                ('base_stamina', models.PositiveIntegerField(default=80, verbose_name='استقامت پایه PES')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='packs/players/', verbose_name='تصویر کارت بازیکن')),
                ('rarity', models.CharField(default='REGULAR', max_length=20, verbose_name='درجه کارت (Rarity)')),
                ('wage', models.DecimalField(decimal_places=2, default=100.0, max_digits=12, verbose_name='دستمزد')),
                ('market_value', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15, verbose_name='ارزش بازار (EUR)')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='دریافت شده است؟')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دریافت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('claimed_by_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pack_players', to='teams.team', verbose_name='تیم دریافت کننده')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gacha.pack', verbose_name='پک مربوطه')),
            ],
            options={
                'verbose_name': 'بازیکن پک',
                'verbose_name_plural': 'بازیکنان پک\u200cها',
                'ordering': ['is_claimed', '-overall', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackOpeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('GEMS', 'جم'), ('DIRECT', 'دلار مجازی/مستقیم')], default='GEMS', max_length=10, verbose_name='روش پرداخت')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار انتخاب'), ('COMPLETED', 'تکمیل شده'), ('EXPIRED', 'منقضی شده (برگشت وجه)')], default='PENDING', max_length=15, verbose_name='وضعیت سشن')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضای سشن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('created_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_pack_session', to='teams.player', verbose_name='بازیکن ثبت شده در تیم')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gacha.pack', verbose_name='پک باز شده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sessions', to='teams.team', verbose_name='تیم')),
                ('card_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_card1', to='gacha.packplayer', verbose_name='کارت اول')),
                ('card_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_card2', to='gacha.packplayer', verbose_name='کارت دوم')),
                ('card_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_card3', to='gacha.packplayer', verbose_name='کارت سوم')),
                ('picked_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_picked', to='gacha.packplayer', verbose_name='کارت انتخاب شده')),
            ],
            options={
                'verbose_name': 'سشن باز کردن پک',
                'verbose_name_plural': 'سشن\u200cهای باز کردن پک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GachaPack',
        ),
        migrations.DeleteModel(
            name='GachaPity',
        ),
        migrations.DeleteModel(
            name='PackOpeningLog',
        ),
    ]
