# Generated by Django 6.0.7 on 2026-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0003_pack_remove_packopeninglog_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='custom_card_bg',
            field=models.ImageField(blank=True, null=True, upload_to='packs/card_bgs/', verbose_name='پس\u200cزمینه اختصاصی کارت پک'),
        ),
    ]
