# Generated by Django 6.0.7 on 2026-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0004_pack_custom_card_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='packplayer',
            name='compatible_positions',
            field=models.CharField(blank=True, default='', help_text='لیست سایر پست\u200cهای قابل بازی بازیکن جدا شده با کاما. مثال: RWF,LWF,SS', max_length=100, verbose_name='پست\u200cهای قابل بازی'),
        ),
    ]
