# Generated by Django 6.0.7 on 2026-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0005_packplayer_compatible_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='packplayer',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='packs/clubs/', verbose_name='لوگوی باشگاه دوران پرایم'),
        ),
        migrations.AddField(
            model_name='packplayer',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ملیت بازیکن'),
        ),
        migrations.AddField(
            model_name='packplayer',
            name='prime_club',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='باشگاه دوران پرایم'),
        ),
    ]
