# Generated by Django 6.0.7 on 2026-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0006_packplayer_club_logo_packplayer_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='guarantee_min_ovr',
            field=models.PositiveIntegerField(default=90, help_text='حداقل اورال کارت اول در بین ۳ کارت شانس (مثلاً ۹۰، یا ۰ برای غیرفعال کردن تضمین)', verbose_name='حداقل اورال اسلات تضمینی'),
        ),
        migrations.AddField(
            model_name='pack',
            name='weight_base_tier',
            field=models.PositiveIntegerField(default=10, help_text='ضریب شانس ظاهر شدن بازیکنان اورال زیر ۹۰ (پیش\u200cفرض: ۱۰)', verbose_name='ضریب شانس کارت\u200cهای زیر ۹۰ (Base Tier)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='weight_mid_tier',
            field=models.PositiveIntegerField(default=4, help_text='ضریب شانس ظاهر شدن اسطوره\u200cهای اورال ۹۰ تا ۹۳ (پیش\u200cفرض: ۴)', verbose_name='ضریب شانس کارت\u200cهای ۹۰-۹۳ (Mid Tier)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='weight_top_tier',
            field=models.PositiveIntegerField(default=1, help_text='ضریب شانس ظاهر شدن فوق\u200cستاره\u200cهای اورال ۹۴ به بالا (پیش\u200cفرض: ۱)', verbose_name='ضریب شانس کارت\u200cهای ۹۴+ (Top Tier)'),
        ),
        migrations.AddField(
            model_name='packplayer',
            name='drop_weight',
            field=models.PositiveIntegerField(default=0, help_text='ضریب شانس اختصاصی این کارت (پیش\u200cفرض: ۰ به معنی پیروی خودکار از رده پک)', verbose_name='ضریب شانس اختصاصی (Drop Weight)'),
        ),
    ]
