# Generated by Django 6.0.7 on 2026-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0007_pack_guarantee_min_ovr_pack_weight_base_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='early_bird_boost_pct',
            field=models.PositiveIntegerField(default=50, help_text='درصد افزایش شانس کارت\u200cهای ۹۴+ هنگام پر بودن استخر (پیش\u200cفرض ۵۰٪)', verbose_name='درصد بانس پیشتازان (Early Bird Boost)'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='weight_base_tier',
            field=models.PositiveIntegerField(default=8, help_text='ضریب شانس ظاهر شدن بازیکنان اورال زیر ۹۰ (پیش\u200cفرض: ۸)', verbose_name='ضریب شانس کارت\u200cهای زیر ۹۰ (Base Tier)'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='weight_mid_tier',
            field=models.PositiveIntegerField(default=5, help_text='ضریب شانس ظاهر شدن اسطوره\u200cهای اورال ۹۰ تا ۹۳ (پیش\u200cفرض: ۵)', verbose_name='ضریب شانس کارت\u200cهای ۹۰-۹۳ (Mid Tier)'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='weight_top_tier',
            field=models.PositiveIntegerField(default=3, help_text='ضریب شانس ظاهر شدن فوق\u200cستاره\u200cهای اورال ۹۴ به بالا (پیش\u200cفرض: ۳)', verbose_name='ضریب شانس کارت\u200cهای ۹۴+ (Top Tier)'),
        ),
    ]
