# Generated by Django 6.0.7 on 2026-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0008_pack_early_bird_boost_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='badge_tag',
            field=models.CharField(blank=True, choices=[('', 'بدون برچسب'), ('HOT_DEAL', 'پیشنهاد شگفت\u200cانگیز 🔥'), ('BEST_SELLER', 'پرفروش\u200cترین ⭐'), ('SPECIAL', 'ویژه 💎'), ('BEST_VALUE', 'ارزش خرید بالا ⚡'), ('LIMITED', 'تخفیف محدود ⏳'), ('POPULAR', 'محبوب مربیان 🚀')], default='', max_length=50, verbose_name='برچسب رنگی پک'),
        ),
        migrations.AddField(
            model_name='pack',
            name='custom_tag_color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='پالت رنگ تگ اختصاصی'),
        ),
        migrations.AddField(
            model_name='pack',
            name='custom_tag_text',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='متن تگ اختصاصی'),
        ),
        migrations.AddField(
            model_name='pack',
            name='discount_cost_gems',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف به جم'),
        ),
        migrations.AddField(
            model_name='pack',
            name='discount_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف به دلار'),
        ),
        migrations.AddField(
            model_name='pack',
            name='discount_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پایان تخفیف ساعتی'),
        ),
    ]
