# Generated by Django 6.0.7 on 2026-09-07 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0009_pack_badge_tag_pack_custom_tag_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_loyalty_boost_enabled',
            field=models.BooleanField(default=True, help_text='فعال یا غیرفعال\u200cسازی سیستم بوست شانس پیتی برای خریداران متوالی', verbose_name='فعال بودن بوست وفاداری (Loyalty Boost)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='loyalty_boost_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='ضریب ضرب شانس کارت\u200cهای منتخب هنگام فعال بودن بوست (پیش\u200cفرض: ۲.۵۰)', max_digits=4, verbose_name='ضریب افزایش شانس وفاداری (Boost Multiplier)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='loyalty_boost_threshold',
            field=models.PositiveIntegerField(default=3, help_text='حداقل تعداد پک\u200cهای متوالی بازشده بدون فوق\u200cستاره جهت فعال\u200cسازی بوست (پیش\u200cفرض: ۳)', verbose_name='تعداد خرید برای فعال\u200cسازی بوست (Pity Threshold)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='loyalty_min_ovr',
            field=models.PositiveIntegerField(default=94, help_text='حداقل اورال کارت\u200cهایی که ضریب بوست وفاداری روی آن\u200cها اعمال می\u200cشود (پیش\u200cفرض: ۹۴)', verbose_name='حداقل اورال کارت\u200cهای مشمول بوست وفاداری'),
        ),
    ]
