# Generated by Django 6.0.7 on 2026-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0010_pack_is_loyalty_boost_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='loyalty_mid_step_pct',
            field=models.PositiveIntegerField(default=35, help_text='درصد افزایش شانس کارت\u200cهای اورال ۹۰ تا ۹۳ در هر خرید ناموفق متوالی (پیش\u200cفرض: ۳۵٪)', verbose_name='درصد بوست پله\u200cای کارت\u200cهای میانی باارزش (۹۰-۹۳)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='loyalty_step_boost_pct',
            field=models.PositiveIntegerField(default=15, help_text='درصد افزایش شانس کنترل\u200cشده کارت\u200cهای ۱ درصدی در هر خرید ناموفق متوالی (پیش\u200cفرض: ۱۵٪)', verbose_name='درصد بوست پله\u200cای کارت\u200cهای ۱ درصدی (۹۴+)'),
        ),
    ]
