# Generated by Django 6.0.7 on 2026-09-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0011_pack_loyalty_mid_step_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packopeningsession',
            name='guaranteed_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_guaranteed_pity', to='gacha.packplayer', verbose_name='کارت تضمین\u200cشده پیتی'),
        ),
    ]
