/**
 * Nationality to Flag Emoji mapping for EA Sports FC 26 Card telemetry
 * Supports both Persian and English nation names.
 */
export const NATIONALITY_FLAGS = {
  // Common football powerhouses (Persian & English)
  'برزیل': '🇧🇷',
  'Brazil': '🇧🇷',
  'آرژانتین': '🇦🇷',
  'Argentina': '🇦🇷',
  'فرانسه': '🇫🇷',
  'France': '🇫🇷',
  'پرتغال': '🇵🇹',
  'Portugal': '🇵🇹',
  'آلمان': '🇩🇪',
  'Germany': '🇩🇪',
  'انگلیس': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'انگلستان': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'اسپانیا': '🇪🇸',
  'Spain': '🇪🇸',
  'ایتالیا': '🇮🇹',
  'Italy': '🇮🇹',
  'هلند': '🇳🇱',
  'Netherlands': '🇳🇱',
  'ایران': '🇮🇷',
  'Iran': '🇮🇷',
  'کرواسی': '🇭🇷',
  'Croatia': '🇭🇷',
  'بلژیک': '🇧🇪',
  'Belgium': '🇧🇪',
  'اروگوئه': '🇺🇾',
  'اوروگوئه': '🇺🇾',
  'Uruguay': '🇺🇾',
  'نروژ': '🇳🇴',
  'Norway': '🇳🇴',
  'لهستان': '🇵🇱',
  'Poland': '🇵🇱',
  'مصر': '🇪🇬',
  'Egypt': '🇪🇬',
  'ساحل عاج': '🇨🇮',
  'Ivory Coast': '🇨🇮',
  'کره جنوبی': '🇰🇷',
  'South Korea': '🇰🇷',
  'ژاپن': '🇯🇵',
  'Japan': '🇯🇵',
  'مراکش': '🇲🇦',
  'Morocco': '🇲🇦',
  'سنگال': '🇸🇳',
  'Senegal': '🇸🇳',
  'کلمبیا': '🇨🇴',
  'Colombia': '🇨🇴',
  'نیجریه': '🇳🇬',
  'Nigeria': '🇳🇬',
  'دانمارک': '🇩🇰',
  'Denmark': '🇩🇰',
  'سوئد': '🇸🇪',
  'Sweden': '🇸🇪',
  'سوئیس': '🇨🇭',
  'Switzerland': '🇨🇭',
  'ترکیه': '🇹🇷',
  'Turkey': '🇹🇷',
  'صربستان': '🇷🇸',
  'Serbia': '🇷🇸',
  'الجزایر': '🇩🇿',
  'Algeria': '🇩🇿',
  'شیلی': '🇨🇱',
  'Chile': '🇨🇱',
  'مکزیک': '🇲🇽',
  'Mexico': '🇲🇽',
  'غنا': '🇬🇭',
  'Ghana': '🇬🇭',
  'کامرون': '🇨🇲',
  'Cameroon': '🇨🇲',
  'ولز': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'اسکاتلند': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'اتریش': '🇦🇹',
  'Austria': '🇦🇹',
  'اوکراین': '🇺🇦',
  'Ukraine': '🇺🇦',
  'آمریکا': '🇺🇸',
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'کانادا': '🇨🇦',
  'Canada': '🇨🇦',
  'گرجستان': '🇬🇪',
  'Georgia': '🇬🇪',
  'چک': '🇨🇿',
  'Czechia': '🇨🇿',
  'جمهوری چک': '🇨🇿',
  'مجارستان': '🇭🇺',
  'Hungary': '🇭🇺',
  'یونان': '🇬🇷',
  'Greece': '🇬🇷',
  'اسلواکی': '🇸🇰',
  'Slovakia': '🇸🇰',
  'اسلوونی': '🇸🇮',
  'Slovenia': '🇸🇮',
  'بوسنی': '🇧🇦',
  'Bosnia': '🇧🇦',
  'عربستان': '🇸🇦',
  'Saudi Arabia': '🇸🇦',
  'قطر': '🇶🇦',
  'Qatar': '🇶🇦',
  'امارات': '🇦🇪',
  'UAE': '🇦🇪',
  'استرالیا': '🇦🇺',
  'Australia': '🇦🇺',
  'پرو': '🇵🇪',
  'Peru': '🇵🇪',
  'اکوادور': '🇪🇨',
  'Ecuador': '🇪🇨',
  'پاراگوئه': '🇵🇾',
  'Paraguay': '🇵🇾',
  'ونزوئلا': '🇻🇪',
  'Venezuela': '🇻🇪',
  'ازبکستان': '🇺🇿',
  'Uzbekistan': '🇺🇿',
  'عراق': '🇮🇶',
  'Iraq': '🇮🇶',
};

/**
 * Returns flag emoji for given nationality string, with fallback to globe emoji
 */
export function getNationalityFlag(nationality) {
  if (!nationality) return '🌍';
  const clean = String(nationality).trim();
  return NATIONALITY_FLAGS[clean] || '🌍';
}
