# Generated by Django 6.0.7 on 2026-08-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تیم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/', verbose_name='لوگو')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='بودجه')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بازیکن')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('DMF', 'Defensive Midfielder'), ('CMF', 'Central Midfielder'), ('LMF', 'Left Midfielder'), ('RMF', 'Right Midfielder'), ('AMF', 'Attacking Midfielder'), ('LWF', 'Left Wing Forward'), ('RWF', 'Right Wing Forward'), ('SS', 'Second Striker'), ('CF', 'Center Forward')], max_length=3, verbose_name='پست اصلی')),
                ('overall', models.PositiveIntegerField(verbose_name='اورال (OVR)')),
                ('base_stamina', models.PositiveIntegerField(verbose_name='استقامت پایه PES')),
                ('virtual_stamina', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='استقامت مجازی فعلی')),
                ('x_coord', models.FloatField(default=0.0, verbose_name='مختصات X در ترکیب')),
                ('y_coord', models.FloatField(default=0.0, verbose_name='مختصات Y در ترکیب')),
                ('is_starting', models.BooleanField(default=False, verbose_name='فیکس است؟')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team', verbose_name='تیم فعلی')),
            ],
            options={
                'verbose_name': 'بازیکن',
                'verbose_name_plural': 'بازیکنان',
            },
        ),
    ]
