# Generated by Django 6.0.7 on 2026-08-01 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consecutive_games',
            field=models.PositiveIntegerField(default=0, help_text='تعداد بازی\u200cهایی که بازیکن بدون استراحت بازی کرده.', verbose_name='بازی\u200cهای متوالی'),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت از مصدومیت'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_injured',
            field=models.BooleanField(default=False, verbose_name='مصدوم است؟'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_match_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین بازی'),
        ),
        migrations.AlterField(
            model_name='player',
            name='base_stamina',
            field=models.PositiveIntegerField(help_text='مقدار Stamina ability بازیکن در PES (0-99)', verbose_name='استقامت پایه PES'),
        ),
        migrations.AlterField(
            model_name='player',
            name='virtual_stamina',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='درصد استقامت فعلی بازیکن (0-100). زیر 30 = قفل شده.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='استقامت مجازی فعلی (%)'),
        ),
    ]
