# Generated by Django 6.0.7 on 2026-08-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_consecutive_games_player_injury_return_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='مثال: ارزیابی هفته ۶، ارزیابی نیم\u200cفصل', max_length=50, verbose_name='دوره ارزیابی')),
                ('old_overall', models.PositiveIntegerField(verbose_name='اورال قبلی')),
                ('new_overall', models.PositiveIntegerField(verbose_name='اورال جدید')),
                ('change_amount', models.IntegerField(help_text='مثلاً +2 یا -1', verbose_name='میزان تغییر')),
                ('change_type', models.CharField(choices=[('UPGRADE', 'ارتقا (رشد)'), ('DOWNGRADE', 'افت'), ('NO_CHANGE', 'بدون تغییر')], max_length=10, verbose_name='نوع تغییر')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='میانگین نمره عملکرد')),
                ('games_played', models.PositiveIntegerField(verbose_name='تعداد بازی\u200cهای ارزیابی\u200cشده')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='گل\u200cهای زده در دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت ارزیابی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات و علت تغییر')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='teams.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'تاریخچه رشد/افت بازیکن',
                'verbose_name_plural': 'تاریخچه رشد و افت بازیکنان',
                'ordering': ['-created_at'],
            },
        ),
    ]
