# Generated by Django 6.0.7 on 2026-08-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_playergrowthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_benched_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازی متوالی نیمکت\u200cنشین'),
        ),
        migrations.AddField(
            model_name='player',
            name='potential_ovr',
            field=models.PositiveIntegerField(default=99, verbose_name='سقف پتانسیل (Potential OVR)'),
        ),
        migrations.AddField(
            model_name='player',
            name='rarity',
            field=models.CharField(default='REGULAR', max_length=20, verbose_name='درجه کارت (Rarity)'),
        ),
        migrations.AddField(
            model_name='player',
            name='suspension_matches',
            field=models.PositiveIntegerField(default=0, verbose_name='بازی\u200cهای محرومیت'),
        ),
        migrations.AddField(
            model_name='player',
            name='training_points',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز تمرین'),
        ),
        migrations.AddField(
            model_name='player',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='دستمزد'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_card_accumulator',
            field=models.PositiveIntegerField(default=0, verbose_name='کارت زرد تجمیعی'),
        ),
        migrations.AddField(
            model_name='team',
            name='academy_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح آکادمی'),
        ),
        migrations.AddField(
            model_name='team',
            name='wage_cap',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15, verbose_name='سقف دستمزد'),
        ),
        migrations.CreateModel(
            name='ClubFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_level', models.PositiveIntegerField(default=1, verbose_name='سطح سالن بدنسازی')),
                ('medical_level', models.PositiveIntegerField(default=1, verbose_name='سطح مرکز پزشکی')),
                ('training_camp_level', models.PositiveIntegerField(default=1, verbose_name='سطح کمپ تمرینی')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='teams.team')),
            ],
            options={
                'verbose_name': 'تسهیلات باشگاه',
                'verbose_name_plural': 'تسهیلات باشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PlayerAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk_reflexes', models.PositiveIntegerField(default=70)),
                ('gk_reflexes_buffer', models.FloatField(default=0.0)),
                ('gk_catching', models.PositiveIntegerField(default=70)),
                ('gk_catching_buffer', models.FloatField(default=0.0)),
                ('gk_reach', models.PositiveIntegerField(default=70)),
                ('gk_reach_buffer', models.FloatField(default=0.0)),
                ('gk_awareness', models.PositiveIntegerField(default=70)),
                ('gk_awareness_buffer', models.FloatField(default=0.0)),
                ('defensive_awareness', models.PositiveIntegerField(default=70)),
                ('defensive_awareness_buffer', models.FloatField(default=0.0)),
                ('ball_winning', models.PositiveIntegerField(default=70)),
                ('ball_winning_buffer', models.FloatField(default=0.0)),
                ('aggression', models.PositiveIntegerField(default=70)),
                ('aggression_buffer', models.FloatField(default=0.0)),
                ('heading', models.PositiveIntegerField(default=70)),
                ('heading_buffer', models.FloatField(default=0.0)),
                ('speed', models.PositiveIntegerField(default=70)),
                ('speed_buffer', models.FloatField(default=0.0)),
                ('stamina', models.PositiveIntegerField(default=70)),
                ('stamina_buffer', models.FloatField(default=0.0)),
                ('dribbling', models.PositiveIntegerField(default=70)),
                ('dribbling_buffer', models.FloatField(default=0.0)),
                ('low_pass', models.PositiveIntegerField(default=70)),
                ('low_pass_buffer', models.FloatField(default=0.0)),
                ('ball_control', models.PositiveIntegerField(default=70)),
                ('ball_control_buffer', models.FloatField(default=0.0)),
                ('lofted_pass', models.PositiveIntegerField(default=70)),
                ('lofted_pass_buffer', models.FloatField(default=0.0)),
                ('offensive_awareness', models.PositiveIntegerField(default=70)),
                ('offensive_awareness_buffer', models.FloatField(default=0.0)),
                ('finishing', models.PositiveIntegerField(default=70)),
                ('finishing_buffer', models.FloatField(default=0.0)),
                ('curl', models.PositiveIntegerField(default=70)),
                ('curl_buffer', models.FloatField(default=0.0)),
                ('kicking_power', models.PositiveIntegerField(default=70)),
                ('kicking_power_buffer', models.FloatField(default=0.0)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='teams.player')),
            ],
            options={
                'verbose_name': 'مهارت\u200cهای بازیکن',
                'verbose_name_plural': 'مهارت\u200cهای بازیکنان',
            },
        ),
    ]
