# Generated by Django 6.0.7 on 2026-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_player_matches_benched_streak_player_potential_ovr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل استقامت'),
        ),
    ]
