# Generated by Django 6.0.7 on 2026-08-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubfacilities',
            name='academy_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح آکادمی جوانان'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='analytics_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح مرکز آنالیز عملکرد'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='media_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح مرکز رسانه\u200cای'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='pool_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح استخر بازیابی'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='psychology_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح مرکز روان\u200cشناسی'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='scouting_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح اسکوتینگ بین\u200cالمللی'),
        ),
        migrations.AddField(
            model_name='clubfacilities',
            name='stadium_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح استادیوم'),
        ),
    ]
