# Generated by Django 6.0.7 on 2026-08-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_clubfacilities_academy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubfacilities',
            name='analytics_level',
        ),
        migrations.RemoveField(
            model_name='clubfacilities',
            name='media_level',
        ),
        migrations.RemoveField(
            model_name='clubfacilities',
            name='psychology_level',
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='scouting_level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح استعدادیابی بین\u200cالمللی'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='قفل استقامت زیر ۳۰٪'),
        ),
        migrations.CreateModel(
            name='TeamGamePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(default='4-2-1-3', max_length=20, verbose_name='سیستم ترکیب')),
                ('play_style', models.CharField(default='پاسکاری کوتاه (Possession)', max_length=50, verbose_name='سبک بازی')),
                ('defensive_press', models.CharField(default='پرس از جلو (High Press)', max_length=50, verbose_name='فشار دفاعی')),
                ('attacking_level', models.CharField(default='کاملاً هجومی +۲', max_length=30, verbose_name='سطح هجومی')),
                ('offside_trap', models.BooleanField(default=True, verbose_name='تله آفساید')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='تایید و ارسال شده به ادمین')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='زمان ثبت و ارسال')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameplan', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'تاکتیک و ترکیب ارسال\u200cشده تیم',
                'verbose_name_plural': 'تاکتیک\u200cها و ترکیب\u200cهای ارسال\u200cشده تیم\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='PlayerAbilities',
        ),
    ]
