# Generated by Django 6.0.6 on 2026-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_clubfacilities_analytics_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لوگو'),
        ),
    ]
