# Generated by Django 6.0 on 2026-08-06 00:00

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='growth_buffer',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='مانده کسری رشد که در هر دوره ارزیابی روی اورال اعمال می‌شود.',
                max_digits=6,
                verbose_name='بافر رشد',
            ),
        ),
    ]
