# Generated by Django 6.0.7 on 2026-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player_growth_buffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgameplan',
            name='attacking_level',
        ),
        migrations.RemoveField(
            model_name='teamgameplan',
            name='defensive_press',
        ),
        migrations.RemoveField(
            model_name='teamgameplan',
            name='offside_trap',
        ),
        migrations.RemoveField(
            model_name='teamgameplan',
            name='play_style',
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='adv_defense_1',
            field=models.CharField(default='هیچکدام', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='adv_defense_2',
            field=models.CharField(default='هیچکدام', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='adv_offense_1',
            field=models.CharField(default='هیچکدام', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='adv_offense_2',
            field=models.CharField(default='هیچکدام', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='attacking_area',
            field=models.CharField(default='مرکز', max_length=20),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='attacking_style',
            field=models.CharField(default='بازی مالکانه', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='build_up',
            field=models.CharField(default='پاس کوتاه', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='compactness',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='containment_area',
            field=models.CharField(default='میانه', max_length=20),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='defensive_line',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='defensive_style',
            field=models.CharField(default='فشار خط مقدم', max_length=50),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='positioning',
            field=models.CharField(default='حفظ ترکیب', max_length=20),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='pressing',
            field=models.CharField(default='تهاجمی', max_length=20),
        ),
        migrations.AddField(
            model_name='teamgameplan',
            name='support_range',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
