# Generated by Django 6.0.7 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_update_teamgameplan_14_tactic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gems',
            field=models.PositiveIntegerField(default=0, verbose_name='جم (ارز ارتقا/گاچا)'),
        ),
    ]
