# Generated by Django 6.0.7 on 2026-08-10 11:46

from django.db import migrations

def copy_academy_level_forward(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    ClubFacilities = apps.get_model('teams', 'ClubFacilities')
    for team in Team.objects.all():
        facilities, _ = ClubFacilities.objects.get_or_create(team=team)
        if team.academy_level > facilities.academy_level:
            facilities.academy_level = team.academy_level
            facilities.save()

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_gems'),
    ]

    operations = [
        migrations.RunPython(copy_academy_level_forward, migrations.RunPython.noop),
    ]
