# Generated by Django 6.0.7 on 2026-08-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_merge_academy_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='academy_level',
        ),
    ]
