# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_remove_team_academy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_formation',
            field=models.CharField(default='4-3-3', max_length=20, verbose_name='ترکیب پیش\u200cفرض'),
        ),
    ]
