# Generated by Django 6.0.7 on 2026-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_default_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='شماره پیراهن'),
        ),
    ]
