# Generated by Django 6.0.7 on 2026-08-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_player_shirt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfacilities',
            name='academy_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح آکادمی جوانان'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='gym_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح سالن بدنسازی'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='medical_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح مرکز پزشکی'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='pool_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح استخر بازیابی'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='scouting_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح استعدادیابی بین\u200cالمللی'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='stadium_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح استادیوم'),
        ),
        migrations.AlterField(
            model_name='clubfacilities',
            name='training_camp_level',
            field=models.PositiveIntegerField(default=0, verbose_name='سطح کمپ تمرینی'),
        ),
    ]
