# Generated by Django 6.0.7 on 2026-08-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_alter_clubfacilities_academy_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='لول')),
                ('xp_required', models.PositiveIntegerField(verbose_name='XP مورد نیاز برای رسیدن به این لول')),
            ],
            options={
                'verbose_name': 'تنظیمات لول بازیکن',
                'verbose_name_plural': 'تنظیمات لول\u200cهای بازیکن',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='سطح فعلی بازیکن (۱ تا ۲۰). هر لول ability\u200cهای پست\u200cمحور را تقویت می\u200cکند.', verbose_name='لول بازیکن'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, help_text='مجموع کل XP کسب\u200cشده از ابتدا (برای آمار و رتبه\u200cبندی).', verbose_name='XP کل (تجمیعی)'),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='تجربه جمع\u200cشده در لول فعلی. با رسیدن به حد نصاب، لول\u200cآپ اتفاق می\u200cافتد.', verbose_name='XP فعلی'),
        ),
        migrations.CreateModel(
            name='PlayerLevelUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.PositiveIntegerField(verbose_name='لول قبلی')),
                ('new_level', models.PositiveIntegerField(verbose_name='لول جدید')),
                ('xp_source', models.CharField(choices=[('MATCH', 'عملکرد در بازی'), ('FACILITY', 'ارتقای تسهیلات باشگاه'), ('GEM_BOOST', 'ارتقا با جم')], max_length=15, verbose_name='منبع XP')),
                ('xp_amount', models.PositiveIntegerField(verbose_name='مقدار XP اعطا شده')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان لول\u200cآپ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_up_logs', to='teams.player', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'تاریخچه لول\u200cآپ بازیکن',
                'verbose_name_plural': 'تاریخچه لول\u200cآپ\u200cهای بازیکنان',
                'ordering': ['-created_at'],
            },
        ),
    ]
