# Generated by Django 6.0.7 on 2026-08-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_playerlevelconfig_player_level_player_total_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loan_matches_left',
            field=models.PositiveIntegerField(default=0, verbose_name='بازی\u200cهای باقیمانده از قرارداد قرضی'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_out_players', to='teams.team', verbose_name='تیم اصلی (مالک)'),
        ),
    ]
