# Generated by Django 6.0.7 on 2026-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_player_loan_matches_left_player_loan_owner_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubfacilities',
            name='scouting_level',
        ),
    ]
