# Generated by Django 6.0.7 on 2026-08-19 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_remove_clubfacilities_scouting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=15, verbose_name='ارزش پایه / ارزش بازار (EUR)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12, verbose_name='دستمزد'),
        ),
    ]
