# Generated by Django 6.0.7 on 2026-08-19 22:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_player_market_value_alter_player_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='قدرت ستاره تیم (۰.۵ تا ۵)'),
        ),
    ]
