# Generated by Django 6.0.7 on 2026-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_team_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='base_overall',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='اورال اولیه/پایه'),
        ),
    ]
