# Generated by Django 6.0.7 on 2026-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_player_base_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال در سیستم لیگ'),
        ),
    ]
