# Generated by Django 6.0.7 on 2026-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_free_agent',
            field=models.BooleanField(default=False, verbose_name='آزاد شده از تیم / بازیکن آزاد'),
        ),
    ]
