# Generated by Django 6.0.7 on 2026-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_player_is_free_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='custom_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='تصویر اختصاصی بازیکن'),
        ),
    ]
