# Generated by Django 6.0.7 on 2026-08-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_player_custom_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='compatible_positions',
            field=models.CharField(blank=True, default='', help_text='لیست پست\u200cهای قابل بازی بازیکن با کاما جدا شده. مثال: RWF,LWF,RMF', max_length=100, verbose_name='پست\u200cهای قابل بازی'),
        ),
    ]
