# Generated by Django 6.0.7 on 2026-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_player_injury_matches_and_fatigue_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills_data',
            field=models.JSONField(blank=True, default=dict, help_text='اطلاعات لول\u200cها و مقادیر PES مهارت\u200cهای تخصصی بازیکن', verbose_name='داده\u200cهای تقویت مهارت\u200cهای PES'),
        ),
    ]
