# Generated by Django 6.0.7 on 2026-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_player_skills_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgameplan',
            name='players_data',
            field=models.JSONField(blank=True, default=list, verbose_name='چیدمان بازیکنان در ترکیب پیش\u200cفرض'),
        ),
    ]
