# Generated by Django 6.0.7 on 2026-09-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_teamgameplan_players_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='کشور یا ملیت بازیکن (مثال: برزیل، فرانسه)', max_length=60, verbose_name='ملیت'),
        ),
        migrations.AddField(
            model_name='player',
            name='pes_transfer_applied',
            field=models.BooleanField(default=False, help_text='آیا انتقال این بازیکن در ترکیب بازی PES اعمال شده است؟', verbose_name='انتقال در PES اعمال شده است'),
        ),
    ]
