# Generated by Django 6.0.7 on 2026-09-13 11:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_matchteamstat_crosses_matchteamstat_free_kicks_and_more'),
        ('teams', '0032_player_nationality_player_pes_transfer_applied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='transfer_ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='محرومیت از نقل\u200cوانتقالات تا تاریخ'),
        ),
        migrations.CreateModel(
            name='ClubPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('MATCH_DELAY', 'تاخیر در حضور برای مسابقه'), ('NO_GAMEPLAN', 'عدم ثبت یا ارسال ترکیب قبل از مسابقه'), ('MATCH_FIXING_CHEATING', 'تبانی، دستکاری نتایج یا تقلب'), ('UNSPORTSMANLIKE', 'توهین، الفاظ نامناسب یا رفتار غیرورزشی'), ('TRANSFER_VIOLATION', 'تخلف در بازار نقل\u200cوانتقالات'), ('FORFEIT_RAGE_QUIT', 'ترک بازی یکطرفه یا عدم انجام مسابقه'), ('CUSTOM', 'سایر تخلفات (سفارشی)')], default='CUSTOM', max_length=40, verbose_name='نوع تخلف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان حکم انضباطی')),
                ('reason', models.TextField(verbose_name='شرح تخلف و دلایل حکم')),
                ('fine_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='مبلغ جریمه دلاری')),
                ('fine_gems', models.PositiveIntegerField(default=0, verbose_name='مقدار جریمه جم')),
                ('points_deduction', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیاز کسرشده')),
                ('transfer_ban_days', models.PositiveIntegerField(default=0, verbose_name='مدت محرومیت نقل\u200cوانتقالات (روز)')),
                ('transfer_ban_until', models.DateTimeField(blank=True, null=True, verbose_name='محرومیت نقل\u200cوانتقالات تا تاریخ')),
                ('is_warning', models.BooleanField(default=False, verbose_name='اخطار رسمی کتبی')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال / اعمال\u200cشده'), ('REVOKED', 'لغوشده / بخشیده\u200cشده'), ('EXPIRED', 'منقضی\u200cشده')], default='ACTIVE', max_length=20, verbose_name='وضعیت حکم')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو/بخشش')),
                ('revoke_reason', models.TextField(blank=True, default='', verbose_name='علت بخشش یا لغو حکم')),
                ('publish_to_newsroom', models.BooleanField(default=True, verbose_name='انتشار بیانیه در اتاق خبر لیگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور حکم')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_penalties', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده حکم')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_penalties', to=settings.AUTH_USER_MODEL, verbose_name='بخشش\u200cکننده حکم')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='teams.team', verbose_name='تیم متخلف')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='matches.tournament', verbose_name='تورنمنت مربوطه برای کسر امتیاز')),
            ],
            options={
                'verbose_name': 'حکم انضباطی باشگاه',
                'verbose_name_plural': 'احکام انضباطی باشگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
