# Generated by Django 6.0.7 on 2026-09-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_team_transfer_ban_until_clubpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpenalty',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='شماره دادنامه رسمی'),
        ),
        migrations.AddField(
            model_name='clubpenalty',
            name='official_verdict_text',
            field=models.TextField(blank=True, default='', verbose_name='متن کامل دادنامه قضایی'),
        ),
        migrations.AlterField(
            model_name='clubpenalty',
            name='violation_type',
            field=models.CharField(choices=[('MATCH_DELAY', 'تاخیر در حضور برای مسابقه'), ('NO_GAMEPLAN', 'عدم ثبت یا ارسال ترکیب قبل از مسابقه'), ('UNSPORTSMANLIKE', 'توهین، الفاظ نامناسب یا رفتار غیرورزشی'), ('REFEREE_ADMIN_INSULT', 'توهین به داور یا مسئولین برگزاری مسابقات'), ('INELIGIBLE_PLAYER', 'استفاده از بازیکن غیرمجاز یا محروم در ترکیب'), ('FORFEIT_RAGE_QUIT', 'ترک بازی یکطرفه یا عدم انجام مسابقه'), ('TRANSFER_VIOLATION', 'تخلف در بازار نقل\u200cوانتقالات'), ('MATCH_FIXING_CHEATING', 'تبانی، دستکاری نتایج یا تقلب'), ('CUSTOM', 'سایر تخلفات (سفارشی)')], default='CUSTOM', max_length=40, verbose_name='نوع تخلف'),
        ),
    ]
