# Generated by Django 6.0.7 on 2026-09-16 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0019_playermatchstat_detailed_stats'),
        ('teams', '0034_clubpenalty_case_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='تیتر خبر')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='روتیتر / تگ فرعی')),
                ('category', models.CharField(choices=[('TRANSFER', 'نقل\u200cوانتقالات'), ('MATCH', 'مسابقات و نتایج'), ('DISCIPLINARY', 'احکام انضباطی'), ('COACH', 'مربیان و باشگاه\u200cها'), ('GENERAL', 'عمومی و بیانیه\u200cها')], default='GENERAL', max_length=20, verbose_name='دسته\u200cبندی')),
                ('summary', models.TextField(verbose_name='خلاصه کوتاه خبر')),
                ('content', models.TextField(verbose_name='متن کامل گزارش خبری')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس تصویر شاخص')),
                ('source_event_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع رویداد منبع')),
                ('source_event_id', models.CharField(blank=True, default='', max_length=50, verbose_name='شناسه رویداد منبع')),
                ('event_hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='هش یکتای رویداد (ضدتکرار)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده در چنل')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق\u200cشده به بالای فید (Pin)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('reactions_count', models.JSONField(blank=True, default=dict, verbose_name='شمارش واکنش\u200cها')),
                ('author_name', models.CharField(default='اتاق خبر رسمی VML', max_length=100, verbose_name='نویسنده / منبع خبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reports', to='matches.match', verbose_name='مسابقه مرتبط')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_mentions', to='teams.player', verbose_name='بازیکن مرتبط')),
                ('related_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='teams.team', verbose_name='تیم مرتبط')),
            ],
            options={
                'verbose_name': 'خبر مطبوعاتی لیگ',
                'verbose_name_plural': 'اخبار و مطبوعات لیگ',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('fire', '🔥 آتیش'), ('heart', '❤️ قلب'), ('like', '👍 عالی'), ('clap', '👏 تشویق'), ('mindblown', '🤯 برگ\u200cریزون')], max_length=20, verbose_name='نوع واکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت واکنش')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='news.leaguenews', verbose_name='خبر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'واکنش مربی به خبر',
                'verbose_name_plural': 'واکنش\u200cهای مربیان به اخبار',
                'unique_together': {('news', 'user', 'reaction_type')},
            },
        ),
    ]
