# Generated by Django 6.0.7 on 2026-09-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birth_date_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(choices=[('superadmin', 'سوپرادمین (مدیر کل)'), ('referee', 'داور و کنترل مسابقات'), ('financial_manager', 'مدیر مالی و فروشگاه'), ('transfer_manager', 'مدیر نقل\u200cوانتقالات و تیم\u200cها'), ('custom', 'سفارشی')], default='custom', max_length=30, verbose_name='نقش ادمینی')),
                ('title', models.CharField(blank=True, default='ادمین سامانه', max_length=100, verbose_name='عنوان شغلی / مسئولیت')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='لیست کلیدهای دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ادمین',
                'verbose_name_plural': 'پروفایل\u200cهای ادمین\u200cها',
            },
        ),
    ]
