# Generated by Django 6.0.7 on 2026-08-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_season', models.PositiveIntegerField(default=1, verbose_name='فصل جاری')),
                ('current_week', models.PositiveIntegerField(default=1, verbose_name='هفته جاری')),
                ('is_transfer_window_open', models.BooleanField(default=False, verbose_name='پنجره نقل و انتقالات باز است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات سراسری',
                'verbose_name_plural': 'تنظیمات سراسری',
            },
        ),
    ]
