# Generated by Django 6.0.7 on 2026-08-24 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_team_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000000.00'), help_text='مقدار بودجه\u200cای که هنگام ریست بودجه یا ایجاد تیم جدید اعمال می\u200cشود.', max_digits=15, verbose_name='بودجه پیش\u200cفرض تیم\u200cها'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_wage_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='حداکثر دستمزد هفتگی قابل پرداخت توسط هر تیم.', max_digits=15, verbose_name='سقف دستمزد پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='facility_bonus_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='ضریبی که بر تأثیر (بونوس) هر امکانات اعمال می\u200cشود.', max_digits=4, verbose_name='ضریب بونوس امکانات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='facility_max_level',
            field=models.PositiveIntegerField(default=20, help_text='سقف لول قابل دسترسی برای هر تسهیلات باشگاه.', verbose_name='حداکثر سطح امکانات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='facility_upgrade_cost_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='ضریبی که بر هزینه پایه هر ارتقا اعمال می\u200cشود.', max_digits=4, verbose_name='ضریب هزینه ارتقا'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_club_facilities',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن بخش تسهیلات و ارتقای باشگاه.', verbose_name='امکانات و تسهیلات باشگاه'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_gacha',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن باز کردن پک\u200cهای شانس بازیکنان.', verbose_name='سیستم گاچا / بسته\u200cهای شانس'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_game_plan',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن قابلیت ارسال ترکیب توسط مربیان.', verbose_name='ارسال ترکیب و تاکتیک'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_live_broadcast',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن تب پخش زنده مسابقات.', verbose_name='پخش زنده مسابقات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_notifications',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن ارسال نوتیفیکیشن\u200cها به کاربران.', verbose_name='سیستم اطلاع\u200cرسانی'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_registration',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن فرم ثبت\u200cنام و عضویت مربی جدید.', verbose_name='ثبت\u200cنام مربیان جدید'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_season_pass',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن سیستم سیزن پس و تسک\u200cهای هفتگی.', verbose_name='سیزن پس (پاس فصلی)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_store',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن تب فروشگاه و خریدهای درون\u200cبرنامه\u200cای.', verbose_name='فروشگاه و بسته\u200cها'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='feature_transfer_market',
            field=models.BooleanField(default=True, help_text='فعال/غیرفعال کردن تب بازار نقل\u200cوانتقالات در اپلیکیشن.', verbose_name='بازار نقل و انتقالات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gacha_pack_price_gems',
            field=models.PositiveIntegerField(default=500, help_text='تعداد جمی که برای باز کردن یک پک گاچا لازم است.', verbose_name='قیمت هر پک با جم'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gacha_pity_threshold',
            field=models.PositiveIntegerField(default=12, help_text='تعداد پک بدون Legendary برای تضمین دریافت Legendary.', verbose_name='آستانه Pity (تضمین لجندری)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gacha_rate_epic',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='درصد احتمال دریافت بازیکن Epic (OVR 80-86).', max_digits=5, verbose_name='شانس دراپ Epic (%)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gacha_rate_legendary',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='درصد احتمال دریافت بازیکن Legendary (OVR 87+).', max_digits=5, verbose_name='شانس دراپ Legendary (%)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='gacha_rate_rare',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='درصد احتمال دریافت بازیکن Rare (OVR 70-79).', max_digits=5, verbose_name='شانس دراپ Rare (%)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='half_duration_minutes',
            field=models.PositiveIntegerField(default=45, help_text='زمان رسمی هر نیمه در سیستم پخش زنده.', verbose_name='مدت هر نیمه بازی (دقیقه)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='listing_duration_hours',
            field=models.PositiveIntegerField(default=48, help_text='هر لیستینگ بازیکن بعد از این مدت (ساعت) خودکار منقضی می\u200cشود.', verbose_name='مدت زمان لیستینگ (ساعت)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیرات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='max_bid_count',
            field=models.PositiveIntegerField(default=10, help_text='تعداد حداکثری پیشنهادهای فعال همزمان برای هر تیم.', verbose_name='حداکثر تعداد پیشنهاد فعال'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='max_player_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000000.00'), help_text='حداکثر قیمتی که مربی می\u200cتواند بازیکنش را در بازار لیست کند.', max_digits=15, verbose_name='سقف قیمت فروش بازیکن'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='max_substitutions',
            field=models.PositiveIntegerField(default=5, help_text='تعداد تعویض مجاز برای هر تیم در طول بازی.', verbose_name='حداکثر تعویض هر تیم'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='max_team_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('999000000.00'), help_text='حداکثر بودجه\u200cای که یک تیم می\u200cتواند در خزانه خود داشته باشد.', max_digits=15, verbose_name='سقف بودجه تیم'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='pre_match_alert_minutes',
            field=models.PositiveIntegerField(default=15, help_text='چند دقیقه قبل از بازی، هشدار آماده\u200cسازی ترکیب ارسال شود.', verbose_name='اخطار قبل از بازی (دقیقه)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='season_pass_premium_price_gems',
            field=models.PositiveIntegerField(default=1000, help_text='تعداد جم لازم برای خرید نسخه VIP سیزن پس.', verbose_name='قیمت VIP سیزن پس'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='season_pass_xp_per_level',
            field=models.PositiveIntegerField(default=100, help_text='مقدار XP پایه\u200cای برای رسیدن به هر سطح جدید.', verbose_name='XP مورد نیاز هر سطح'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='site_title',
            field=models.CharField(default='Virtual Master League', max_length=150, verbose_name='عنوان سایت'),
        ),
    ]
