# Generated by Django 6.0.7 on 2026-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalsettings_default_team_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='transfer_manual_override',
            field=models.CharField(choices=[('AUTO', 'خودکار طبق تقویم'), ('FORCE_OPEN', 'اجباراً باز'), ('FORCE_CLOSED', 'اجباراً بسته')], default='AUTO', max_length=15, verbose_name='حالت پنجره نقل و انتقالات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='transfer_market_auto_schedule',
            field=models.BooleanField(default=True, help_text='باز شدن خودکار بازار در روزهای استراحت (ساعت ۰۰:۰۰ تا ۱۸:۰۰)', verbose_name='زمان\u200cبندی خودکار پنجره نقل\u200cوانتقالات'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='transfer_window_close_hour',
            field=models.PositiveIntegerField(default=18, verbose_name='ساعت پایان بازار (روز استراحت)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='transfer_window_open_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت شروع بازار (روز استراحت)'),
        ),
    ]
